--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_ASSESS
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_ASSESS" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"TEMPLATE_ID" NUMBER, 
	"LISTEDNESS" NUMBER, 
	"UPDATED" DATE, 
	"OUTCOME" NUMBER, 
	"COMMENT_ID" NUMBER, 
	"COMP_COMMENT_ID" NUMBER, 
	"SERIOUSNESS" NUMBER, 
	"SERIOUS_NOTES" VARCHAR2(1000 CHAR), 
	"AGENT_SUSPECT" NUMBER, 
	"AGENT_NOTES" VARCHAR2(1000 CHAR), 
	"LISTEDNESS_NOTES" VARCHAR2(1000 CHAR), 
	"BFARM_CAUSALITY" NUMBER(10,0), 
	"BFARM_MANUAL_TEXT" CLOB, 
	"COMPANY_DIAGNOSIS" VARCHAR2(250 CHAR), 
	"COMPANY_DIAGNOSIS_NOTES" VARCHAR2(1000 CHAR), 
	"DIAGNOSIS_DICT_ID" NUMBER, 
	"DIAGNOSIS_PREF_CODE" VARCHAR2(30 CHAR), 
	"DIAGNOSIS_INC_CODE" VARCHAR2(30 CHAR), 
	"DIAGNOSIS_INC_TERM" VARCHAR2(250 CHAR), 
	"DIAGNOSIS_HLGT_CODE" VARCHAR2(30 CHAR), 
	"DIAGNOSIS_HLGT" VARCHAR2(250 CHAR), 
	"DIAGNOSIS_HLT_CODE" VARCHAR2(30 CHAR), 
	"DIAGNOSIS_HLT" VARCHAR2(250 CHAR), 
	"DIAGNOSIS_SOC_CODE" VARCHAR2(30 CHAR), 
	"DIAGNOSIS_BODY_SYS" VARCHAR2(250 CHAR), 
	"UD_TEXT_1" VARCHAR2(100 CHAR), 
	"UD_TEXT_2" VARCHAR2(100 CHAR), 
	"UD_TEXT_3" VARCHAR2(100 CHAR), 
	"UD_TEXT_4" VARCHAR2(100 CHAR), 
	"UD_TEXT_5" VARCHAR2(100 CHAR), 
	"UD_TEXT_6" VARCHAR2(100 CHAR), 
	"UD_TEXT_7" VARCHAR2(100 CHAR), 
	"UD_TEXT_8" VARCHAR2(100 CHAR), 
	"UD_TEXT_9" VARCHAR2(100 CHAR), 
	"UD_TEXT_10" VARCHAR2(100 CHAR), 
	"UD_TEXT_11" VARCHAR2(100 CHAR), 
	"UD_TEXT_12" VARCHAR2(100 CHAR), 
	"UD_DATE_1" DATE, 
	"UD_DATE_2" DATE, 
	"UD_DATE_3" DATE, 
	"UD_DATE_4" DATE, 
	"UD_DATE_5" DATE, 
	"UD_DATE_6" DATE, 
	"UD_DATE_7" DATE, 
	"UD_DATE_8" DATE, 
	"UD_DATE_9" DATE, 
	"UD_DATE_10" DATE, 
	"UD_DATE_11" DATE, 
	"UD_DATE_12" DATE, 
	"UD_NUMBER_1" NUMBER(30,10), 
	"UD_NUMBER_2" NUMBER(30,10), 
	"UD_NUMBER_3" NUMBER(30,10), 
	"UD_NUMBER_4" NUMBER(30,10), 
	"UD_NUMBER_5" NUMBER(30,10), 
	"UD_NUMBER_6" NUMBER(30,10), 
	"UD_NUMBER_7" NUMBER(30,10), 
	"UD_NUMBER_8" NUMBER(30,10), 
	"UD_NUMBER_9" NUMBER(30,10), 
	"UD_NUMBER_10" NUMBER(30,10), 
	"UD_NUMBER_11" NUMBER(30,10), 
	"UD_NUMBER_12" NUMBER(30,10), 
	"EVALUATION" CLOB, 
	"EVALUATION_J" CLOB, 
	"CO_SUSPECT_COUNT" NUMBER(3,0), 
	"EVENT_SYNOPSIS" VARCHAR2(5 CHAR), 
	"EVENT_PRIMARY" VARCHAR2(400 CHAR), 
	"DIAGNOSIS_REPTD" VARCHAR2(255 CHAR), 
	"DIAGNOSIS_CODED" VARCHAR2(255 CHAR), 
	"DIAGNOSIS_SYN_CODE" NUMBER, 
	"DIAGNOSIS_CODE_STATUS" NUMBER(3,0), 
	"EVENT_PRIMARY_J" VARCHAR2(400 CHAR), 
	"AGENT_NOTES_J" VARCHAR2(1000 CHAR), 
	"COMPANY_DIAGNOSIS_J" VARCHAR2(250 CHAR), 
	"COMPANY_DIAGNOSIS_NOTES_J" VARCHAR2(1000 CHAR), 
	"DIAGNOSIS_BODY_SYS_J" VARCHAR2(250 CHAR), 
	"DIAGNOSIS_CODED_J" VARCHAR2(255 CHAR), 
	"DIAGNOSIS_CODE_STATUS_J" NUMBER, 
	"DIAGNOSIS_HLGT_J" VARCHAR2(250 CHAR), 
	"DIAGNOSIS_HLT_J" VARCHAR2(250 CHAR), 
	"DIAGNOSIS_INC_CODE_J" VARCHAR2(30 CHAR), 
	"DIAGNOSIS_INC_TERM_J" VARCHAR2(250 CHAR), 
	"DIAGNOSIS_REPTD_J" VARCHAR2(255 CHAR), 
	"LISTEDNESS_NOTES_J" VARCHAR2(1000 CHAR), 
	"SERIOUS_NOTES_J" VARCHAR2(1000 CHAR), 
	"UD_TEXT_1_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_2_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_3_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_4_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_5_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_6_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_7_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_8_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_9_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_10_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_11_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_12_J" VARCHAR2(100 CHAR), 
	"DIAGNOSIS_SYN_CODE_J" NUMBER, 
	"DELETED" DATE, 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" 
 LOB ("BFARM_MANUAL_TEXT") STORE AS BASICFILE "RCA_BFARM_MANUAL_TEXT_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EVALUATION") STORE AS BASICFILE "RCA_EVALUATION_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EVALUATION_J") STORE AS BASICFILE "RCA_EVALUATION_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_ASSESS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_ASSESS" ON "MART_USER"."RM_CASE_ASSESS" ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_ASSESS
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_ASSESS" ON "MART_USER"."RM_CASE_ASSESS" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_ASSESS
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_ASSESS" ADD CONSTRAINT "PK_RM_CASE_ASSESS" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_ASSESS" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_ASSESS" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_ASSESS" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_ASSESS" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_CLASSIFICATIONS
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_CLASSIFICATIONS" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"SEQ_NUM" NUMBER, 
	"CLASSIFICATION_ID" NUMBER, 
	"DELETED" DATE, 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_CLASSIFICATIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_CLASSIFICATIONS" ON "MART_USER"."RM_CASE_CLASSIFICATIONS" ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_CLASSIFICATIONS
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_CLASSIFICATIONS" ON "MART_USER"."RM_CASE_CLASSIFICATIONS" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_CLASSIFICATIONS
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_CLASSIFICATIONS" ADD CONSTRAINT "PK_RM_CASE_CLASSIFICATIONS" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_CLASSIFICATIONS" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_CLASSIFICATIONS" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_CLASSIFICATIONS" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_CLASSIFICATIONS" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_EVENT
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_EVENT" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"SEQ_NUM" NUMBER, 
	"DESC_REPTD" VARCHAR2(250 CHAR), 
	"DESC_CODED" VARCHAR2(255 CHAR), 
	"DIAGNOSIS" NUMBER, 
	"ONSET" DATE, 
	"ONSET_RES" NUMBER, 
	"ONSET_DELAY" VARCHAR2(40 CHAR), 
	"STOP_DATE" DATE, 
	"STOP_DATE_RES" NUMBER, 
	"DURATION" VARCHAR2(40 CHAR), 
	"ONSET_LATENCY" VARCHAR2(40 CHAR), 
	"EVT_INTENSITY_ID" NUMBER, 
	"EVT_FREQ_ID" NUMBER, 
	"TREATED" NUMBER, 
	"STUDY_RELATED" NUMBER, 
	"RECHALL_RELATED" NUMBER, 
	"PROD_SEQ_NUM" NUMBER, 
	"EVT_OUTCOME_ID" NUMBER, 
	"RECEIPT_DATE" DATE, 
	"RPT_SERIOUS" NUMBER, 
	"SC_DEATH" NUMBER, 
	"SC_HOSP" NUMBER, 
	"SC_CONG_ANOM" NUMBER, 
	"SC_THREAT" NUMBER, 
	"SC_DISABLE" NUMBER, 
	"SC_INT_REQ" NUMBER, 
	"SC_OTHER" NUMBER, 
	"SC_OTHER_TEXT" VARCHAR2(30 CHAR), 
	"ART_CODE" VARCHAR2(30 CHAR), 
	"PREF_TERM" VARCHAR2(250 CHAR), 
	"INC_TERM" VARCHAR2(250 CHAR), 
	"BODY_SYS" VARCHAR2(250 CHAR), 
	"MED_SERIOUS" NUMBER, 
	"PAST_HIST" NUMBER, 
	"DICT_ID" NUMBER, 
	"DICT_KEY" VARCHAR2(20 CHAR), 
	"CODE_STATUS" NUMBER, 
	"SERIOUSNESS" NUMBER, 
	"SORT_ID" NUMBER, 
	"ONSET_DATE_PARTIAL" VARCHAR2(20 CHAR), 
	"STOP_DATE_PARTIAL" VARCHAR2(20 CHAR), 
	"EFFICACY" NUMBER, 
	"DISEASE" NUMBER, 
	"WITHDRAWAL" NUMBER, 
	"HLGT" VARCHAR2(250 CHAR), 
	"HLT" VARCHAR2(250 CHAR), 
	"HLT_CODE" VARCHAR2(30 CHAR), 
	"HLGT_CODE" VARCHAR2(30 CHAR), 
	"SOC_CODE" VARCHAR2(30 CHAR), 
	"STUDY_DROPPED" NUMBER(4,0), 
	"INC_CODE" VARCHAR2(30 CHAR), 
	"ONSET_MINUTES" NUMBER, 
	"DELAY_MINUTES" NUMBER, 
	"UD_TEXT_1" VARCHAR2(100 CHAR), 
	"UD_TEXT_2" VARCHAR2(100 CHAR), 
	"UD_TEXT_3" VARCHAR2(100 CHAR), 
	"UD_TEXT_4" VARCHAR2(100 CHAR), 
	"UD_TEXT_5" VARCHAR2(100 CHAR), 
	"UD_TEXT_6" VARCHAR2(100 CHAR), 
	"UD_TEXT_7" VARCHAR2(100 CHAR), 
	"UD_TEXT_8" VARCHAR2(100 CHAR), 
	"UD_TEXT_9" VARCHAR2(100 CHAR), 
	"UD_TEXT_10" VARCHAR2(100 CHAR), 
	"UD_TEXT_11" VARCHAR2(100 CHAR), 
	"UD_TEXT_12" VARCHAR2(100 CHAR), 
	"UD_DATE_1" DATE, 
	"UD_DATE_2" DATE, 
	"UD_DATE_3" DATE, 
	"UD_DATE_4" DATE, 
	"UD_DATE_5" DATE, 
	"UD_DATE_6" DATE, 
	"UD_DATE_7" DATE, 
	"UD_DATE_8" DATE, 
	"UD_DATE_9" DATE, 
	"UD_DATE_10" DATE, 
	"UD_DATE_11" DATE, 
	"UD_DATE_12" DATE, 
	"UD_NUMBER_1" NUMBER(30,10), 
	"UD_NUMBER_2" NUMBER(30,10), 
	"UD_NUMBER_3" NUMBER(30,10), 
	"UD_NUMBER_4" NUMBER(30,10), 
	"UD_NUMBER_5" NUMBER(30,10), 
	"UD_NUMBER_6" NUMBER(30,10), 
	"UD_NUMBER_7" NUMBER(30,10), 
	"UD_NUMBER_8" NUMBER(30,10), 
	"UD_NUMBER_9" NUMBER(30,10), 
	"UD_NUMBER_10" NUMBER(30,10), 
	"UD_NUMBER_11" NUMBER(30,10), 
	"UD_NUMBER_12" NUMBER(30,10), 
	"DETAILS" CLOB, 
	"DETAILS_J" CLOB, 
	"SYN_CODE" NUMBER, 
	"DELETED" DATE, 
	"STUDY_RELATED_REPTD" NUMBER(1,0), 
	"DURATION_UNIT_E2B" NUMBER, 
	"ONSET_LATENCY_UNIT_E2B" NUMBER, 
	"ONSET_DELAY_UNIT_E2B" NUMBER, 
	"DURATION_SECONDS" NUMBER, 
	"ONSET_LATENCY_SECONDS" NUMBER, 
	"ONSET_DELAY_SECONDS" NUMBER, 
	"BODY_SYS_J" VARCHAR2(250 CHAR), 
	"CODE_STATUS_J" NUMBER, 
	"DESC_CODED_J" VARCHAR2(255 CHAR), 
	"DESC_REPTD_J" VARCHAR2(250 CHAR), 
	"HLGT_J" VARCHAR2(250 CHAR), 
	"HLT_J" VARCHAR2(250 CHAR), 
	"INC_CODE_J" VARCHAR2(30 CHAR), 
	"INC_TERM_J" VARCHAR2(250 CHAR), 
	"PREF_TERM_J" VARCHAR2(250 CHAR), 
	"SC_OTHER_TEXT_J" VARCHAR2(30 CHAR), 
	"REPORT_EXCLUSION" NUMBER, 
	"REPORTABLE" NUMBER, 
	"UD_TEXT_1_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_2_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_3_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_4_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_5_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_6_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_7_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_8_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_9_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_10_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_11_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_12_J" VARCHAR2(100 CHAR), 
	"SYN_CODE_J" NUMBER, 
	"INFECTION" NUMBER, 
	"RPT_EXCLUDE_CMT" VARCHAR2(1000 CHAR), 
	"RPT_EXCLUDE_CMT_J" VARCHAR2(1000 CHAR), 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" 
 LOB ("DETAILS") STORE AS BASICFILE "RCE_DETAILS_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DETAILS_J") STORE AS BASICFILE "RCE_DETAILS_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_EVENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_EVENT" ON "MART_USER"."RM_CASE_EVENT" ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_EVENT
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_EVENT" ON "MART_USER"."RM_CASE_EVENT" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_EVENT
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_EVENT" ADD CONSTRAINT "PK_RM_CASE_EVENT" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_EVENT_ASSESS
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_EVENT_ASSESS" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"EVENT_SEQ_NUM" NUMBER, 
	"PROD_SEQ_NUM" NUMBER, 
	"DATASHEET_ID" NUMBER, 
	"LICENSE_ID" NUMBER, 
	"SEQ_NUM" NUMBER, 
	"UPDATED" DATE, 
	"DET_LISTEDNESS_ID" NUMBER, 
	"RPT_CAUSALITY_ID" NUMBER, 
	"DET_CAUSALITY_ID" NUMBER, 
	"LISTED_JUSTIFY" VARCHAR2(1000 CHAR), 
	"CAUSE_JUSTIFY" VARCHAR2(1000 CHAR), 
	"LAM_ASSESSED" NUMBER(12,0), 
	"DELETED" DATE, 
	"CAUSALITY_ASSESSMENT" VARCHAR2(50 CHAR), 
	"CAUSALITY_SCORE" NUMBER, 
	"SOURCE_ID" NUMBER, 
	"PRT_CAUSALITY_ID" NUMBER, 
	"CAUSE_JUSTIFY_J" VARCHAR2(1000 CHAR), 
	"LISTED_JUSTIFY_J" VARCHAR2(1000 CHAR), 
	"DLP_REVISION_NUMBER" NUMBER, 
	"LAST_UPDATE_TIME" DATE, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_EVENT_ASSESS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_EVENT_ASSESS" ON "MART_USER"."RM_CASE_EVENT_ASSESS" ("ENTERPRISE_ID", "CASE_ID", "EVENT_SEQ_NUM", "PROD_SEQ_NUM", "DATASHEET_ID", "LICENSE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_EVENT_ASSESS
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_EVENT_ASSESS" ON "MART_USER"."RM_CASE_EVENT_ASSESS" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_EVENT_ASSESS
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_EVENT_ASSESS" ADD CONSTRAINT "PK_RM_CASE_EVENT_ASSESS" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "EVENT_SEQ_NUM", "PROD_SEQ_NUM", "DATASHEET_ID", "LICENSE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT_ASSESS" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT_ASSESS" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT_ASSESS" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT_ASSESS" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_FOLLOWUP
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_FOLLOWUP" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"SEQ_NUM" NUMBER, 
	"RECEIPT_DATE" DATE, 
	"SAFETY_DATE" DATE, 
	"SIGNIFICANT" NUMBER(1,0), 
	"AUDITLOG_TYPE" NUMBER, 
	"TIME_STAMP" DATE, 
	"DELETED" DATE, 
	"SIGNIFICANT_DEVICE" NUMBER(1,0), 
	"DATA_CLEANUP" NUMBER(1,0), 
	"JUSTIFICATION" VARCHAR2(1000 CHAR), 
	"JUSTIFICATION_ID" NUMBER, 
	"JUSTIFICATION_J" VARCHAR2(1000 CHAR), 
	"JUST_RECEIPT_DATE_J" VARCHAR2(1000 CHAR), 
	"RECEIPT_DATE_J" DATE, 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_FOLLOWUP
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_FOLLOWUP" ON "MART_USER"."RM_CASE_FOLLOWUP" ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_FOLLOWUP
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_FOLLOWUP" ON "MART_USER"."RM_CASE_FOLLOWUP" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_FOLLOWUP
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_FOLLOWUP" ADD CONSTRAINT "PK_RM_CASE_FOLLOWUP" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_FOLLOWUP" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_FOLLOWUP" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_FOLLOWUP" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_FOLLOWUP" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_MASTER
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_MASTER" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"CASE_NUM" VARCHAR2(20 CHAR), 
	"REV" NUMBER, 
	"WORKFLOW_SEQ_NUM" NUMBER, 
	"LAST_WORKFLOW_SEQ_NUM" NUMBER, 
	"CREATE_TIME" DATE, 
	"INIT_REPT_DATE" DATE, 
	"USER_ID" NUMBER, 
	"LAST_UPDATE_TIME" DATE, 
	"LAST_UPDATE_USER_ID" NUMBER, 
	"REQUIRES_FOLLOWUP" NUMBER, 
	"FOLLOWUP_DATE" DATE, 
	"OWNER_ID" NUMBER, 
	"STATE_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"LANG_ID" NUMBER, 
	"PRIORITY" NUMBER, 
	"SITE_ID" NUMBER, 
	"SERIOUSNESS" NUMBER, 
	"RPT_TYPE_ID" NUMBER, 
	"LAST_STATE_ID" NUMBER, 
	"ASSESSMENT_NEEDED" NUMBER, 
	"PRIORITY_OVERRIDE" NUMBER(1,0), 
	"SID" VARCHAR2(128 CHAR), 
	"SAFETY_DATE" DATE, 
	"NORMAL_TIME" DATE, 
	"MAX_TIME" DATE, 
	"REPORT_SCHEDULING" NUMBER, 
	"PRIORITY_ASSESSMENT" NUMBER, 
	"CLOSE_USER_ID" NUMBER, 
	"CLOSE_DATE" DATE, 
	"CLOSE_NOTES" VARCHAR2(200 CHAR), 
	"DATE_LOCKED" DATE, 
	"UD_TEXT_1" VARCHAR2(100 CHAR), 
	"UD_TEXT_2" VARCHAR2(100 CHAR), 
	"UD_TEXT_3" VARCHAR2(100 CHAR), 
	"UD_TEXT_4" VARCHAR2(100 CHAR), 
	"UD_TEXT_5" VARCHAR2(100 CHAR), 
	"UD_TEXT_6" VARCHAR2(100 CHAR), 
	"UD_TEXT_7" VARCHAR2(100 CHAR), 
	"UD_TEXT_8" VARCHAR2(100 CHAR), 
	"UD_TEXT_9" VARCHAR2(100 CHAR), 
	"UD_TEXT_10" VARCHAR2(100 CHAR), 
	"UD_TEXT_11" VARCHAR2(100 CHAR), 
	"UD_TEXT_12" VARCHAR2(100 CHAR), 
	"UD_DATE_1" DATE, 
	"UD_DATE_2" DATE, 
	"UD_DATE_3" DATE, 
	"UD_DATE_4" DATE, 
	"UD_DATE_5" DATE, 
	"UD_DATE_6" DATE, 
	"UD_DATE_7" DATE, 
	"UD_DATE_8" DATE, 
	"UD_DATE_9" DATE, 
	"UD_DATE_10" DATE, 
	"UD_DATE_11" DATE, 
	"UD_DATE_12" DATE, 
	"UD_NUMBER_1" NUMBER(30,10), 
	"UD_NUMBER_2" NUMBER(30,10), 
	"UD_NUMBER_3" NUMBER(30,10), 
	"UD_NUMBER_4" NUMBER(30,10), 
	"UD_NUMBER_5" NUMBER(30,10), 
	"UD_NUMBER_6" NUMBER(30,10), 
	"UD_NUMBER_7" NUMBER(30,10), 
	"UD_NUMBER_8" NUMBER(30,10), 
	"UD_NUMBER_9" NUMBER(30,10), 
	"UD_NUMBER_10" NUMBER(30,10), 
	"UD_NUMBER_11" NUMBER(30,10), 
	"UD_NUMBER_12" NUMBER(30,10), 
	"DELETED" DATE, 
	"DUE_SOON" DATE, 
	"GLOBAL_NUM" VARCHAR2(20 CHAR), 
	"PRIORITY_DATE_ASSESSED" DATE, 
	"LAM_ASSESS_DONE" NUMBER(1,0), 
	"E2B_WW_NUMBER" VARCHAR2(100 CHAR), 
	"WORKLIST_OWNER_ID" NUMBER, 
	"SUSAR" NUMBER, 
	"LAST_UPDATE_EVENT" DATE, 
	"INITIAL_JUSTIFICATION" VARCHAR2(1000 CHAR), 
	"FORCE_SOON" DATE, 
	"DUE_SOON_J" DATE, 
	"FOLLOWUP_DATE_J" DATE, 
	"INIT_REPT_DATE_J" DATE, 
	"JUST_INIT_REPT_DATE_J" VARCHAR2(1000 CHAR), 
	"UD_TEXT_1_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_2_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_3_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_4_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_5_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_6_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_7_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_8_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_9_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_10_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_11_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_12_J" VARCHAR2(100 CHAR), 
	"INITIAL_JUSTIFICATION_J" VARCHAR2(1000 CHAR), 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_MASTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_MASTER" ON "MART_USER"."RM_CASE_MASTER" ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_MASTER
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_MASTER" ON "MART_USER"."RM_CASE_MASTER" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_MASTER
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_MASTER" ADD CONSTRAINT "PK_RM_CASE_MASTER" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_MASTER" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_MASTER" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_MASTER" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_MASTER" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_NARRATIVE
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_NARRATIVE" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"ABBREV_NARRATIVE" CLOB DEFAULT EMPTY_CLOB(), 
	"ABBREV_NARRATIVE_J" CLOB, 
	"NARRATIVE" CLOB, 
	"NARRATIVE_J" CLOB, 
	"DELETED" DATE, 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" 
 LOB ("ABBREV_NARRATIVE") STORE AS BASICFILE "RCN_ABBREV_NARRATIVE_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ABBREV_NARRATIVE_J") STORE AS BASICFILE "RCN_ABBREV_NARRATIVE_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("NARRATIVE") STORE AS BASICFILE "RCN_NARRATIVE_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("NARRATIVE_J") STORE AS BASICFILE "RCN_NARRATIVE_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_NARRATIVE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_NARRATIVE" ON "MART_USER"."RM_CASE_NARRATIVE" ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_NARRATIVE
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_NARRATIVE" ON "MART_USER"."RM_CASE_NARRATIVE" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_NARRATIVE
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_NARRATIVE" ADD CONSTRAINT "PK_RM_CASE_NARRATIVE" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_NARRATIVE" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_NARRATIVE" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_NARRATIVE" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_NARRATIVE" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_PAT_INFO
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_PAT_INFO" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"PAT_ID" VARCHAR2(10 CHAR), 
	"PAT_SUBJ_NUM" VARCHAR2(20 CHAR), 
	"PAT_INITIALS" VARCHAR2(10 CHAR), 
	"PAT_FIRSTNAME" VARCHAR2(35 CHAR), 
	"PAT_MI" VARCHAR2(15 CHAR), 
	"PAT_LASTNAME" VARCHAR2(50 CHAR), 
	"PAT_ADDRESS" VARCHAR2(120 CHAR), 
	"PAT_CITY" VARCHAR2(35 CHAR), 
	"PAT_STATE" VARCHAR2(40 CHAR), 
	"PAT_POSTAL_CODE" VARCHAR2(15 CHAR), 
	"PAT_COUNTRY" VARCHAR2(50 CHAR), 
	"PAT_PHONE" VARCHAR2(20 CHAR), 
	"PAT_DOB" DATE, 
	"PAT_DOB_RES" NUMBER, 
	"PAT_AGE" NUMBER(22,7), 
	"AGE_UNIT_ID" NUMBER, 
	"AGE_GROUP_ID" NUMBER, 
	"GENDER_ID" NUMBER, 
	"PAT_WEIGHT_LBS" NUMBER(22,7), 
	"PAT_WEIGHT_KG" NUMBER(22,7), 
	"PAT_HEIGHT_IN" NUMBER(22,7), 
	"PAT_HEIGHT_CM" NUMBER(22,7), 
	"ETHNICITY_ID" NUMBER, 
	"OCCUPATION_ID" NUMBER, 
	"PAT_STAT_PREG" NUMBER, 
	"REL_TEST_ID" NUMBER, 
	"PAT_DOB_PARTIAL" VARCHAR2(20 CHAR), 
	"RAND_NUM" VARCHAR2(15 CHAR), 
	"CONFIDENTIAL" NUMBER(1,0), 
	"NUMBER_OF_PATIENTS" VARCHAR2(8 CHAR), 
	"UD_TEXT_1" VARCHAR2(100 CHAR), 
	"UD_TEXT_2" VARCHAR2(100 CHAR), 
	"UD_TEXT_3" VARCHAR2(100 CHAR), 
	"UD_TEXT_4" VARCHAR2(100 CHAR), 
	"UD_TEXT_5" VARCHAR2(100 CHAR), 
	"UD_TEXT_6" VARCHAR2(100 CHAR), 
	"UD_TEXT_7" VARCHAR2(100 CHAR), 
	"UD_TEXT_8" VARCHAR2(100 CHAR), 
	"UD_TEXT_9" VARCHAR2(100 CHAR), 
	"UD_TEXT_10" VARCHAR2(100 CHAR), 
	"UD_TEXT_11" VARCHAR2(100 CHAR), 
	"UD_TEXT_12" VARCHAR2(100 CHAR), 
	"UD_DATE_1" DATE, 
	"UD_DATE_2" DATE, 
	"UD_DATE_3" DATE, 
	"UD_DATE_4" DATE, 
	"UD_DATE_5" DATE, 
	"UD_DATE_6" DATE, 
	"UD_DATE_7" DATE, 
	"UD_DATE_8" DATE, 
	"UD_DATE_9" DATE, 
	"UD_DATE_10" DATE, 
	"UD_DATE_11" DATE, 
	"UD_DATE_12" DATE, 
	"UD_NUMBER_1" NUMBER(30,10), 
	"UD_NUMBER_2" NUMBER(30,10), 
	"UD_NUMBER_3" NUMBER(30,10), 
	"UD_NUMBER_4" NUMBER(30,10), 
	"UD_NUMBER_5" NUMBER(30,10), 
	"UD_NUMBER_6" NUMBER(30,10), 
	"UD_NUMBER_7" NUMBER(30,10), 
	"UD_NUMBER_8" NUMBER(30,10), 
	"UD_NUMBER_9" NUMBER(30,10), 
	"UD_NUMBER_10" NUMBER(30,10), 
	"UD_NUMBER_11" NUMBER(30,10), 
	"UD_NUMBER_12" NUMBER(30,10), 
	"DELETED" DATE, 
	"CHILD_ONLY" NUMBER(1,0), 
	"PAT_BMI" NUMBER(22,7), 
	"PAT_BODY_AREA" NUMBER(22,7), 
	"PAT_ADDRESS_J" VARCHAR2(120 CHAR), 
	"PAT_CITY_J" VARCHAR2(35 CHAR), 
	"PAT_FIRSTNAME_J" VARCHAR2(35 CHAR), 
	"PAT_LASTNAME_J" VARCHAR2(50 CHAR), 
	"PAT_MI_J" VARCHAR2(15 CHAR), 
	"PAT_STATE_J" VARCHAR2(40 CHAR), 
	"UD_TEXT_1_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_2_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_3_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_4_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_5_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_6_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_7_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_8_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_9_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_10_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_11_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_12_J" VARCHAR2(100 CHAR), 
	"PAT_COUNTRY_ID" NUMBER, 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"NOTES" CLOB, 
	"NOTES_J" CLOB, 
	"AGE_UNIT_ID_AT_VACC" NUMBER, 
	"PAT_AGE_AT_VACC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" 
 LOB ("NOTES") STORE AS BASICFILE "RCPI_NOTES_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("NOTES_J") STORE AS BASICFILE "RCPI_NOTES_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_PAT_INFO
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_PAT_INFO" ON "MART_USER"."RM_CASE_PAT_INFO" ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_PAT_INFO
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_PAT_INFO" ON "MART_USER"."RM_CASE_PAT_INFO" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_PAT_INFO
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_PAT_INFO" ADD CONSTRAINT "PK_RM_CASE_PAT_INFO" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_PAT_INFO" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PAT_INFO" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PAT_INFO" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PAT_INFO" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_PROD_DRUGS
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_PROD_DRUGS" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"SEQ_NUM" NUMBER, 
	"FORMULATION_ID" NUMBER, 
	"CONCENTRATION" VARCHAR2(10 CHAR), 
	"CONC_UNITS_ID" NUMBER, 
	"ACT_TAKEN_ID" NUMBER, 
	"SEVERITY_ID" NUMBER, 
	"INTERACTION" NUMBER, 
	"CONTRAIND" NUMBER, 
	"FIRST_DOSE" DATE, 
	"FIRST_DOSE_RES" NUMBER, 
	"LAST_DOSE" DATE, 
	"LAST_DOSE_RES" NUMBER, 
	"TOTAL_DOSE" NUMBER(22,7), 
	"TOT_DOSE_UNIT_ID" NUMBER, 
	"PREV_USE" NUMBER, 
	"ABUSE" NUMBER, 
	"OVERDOSE" NUMBER, 
	"PROTOCOL" NUMBER, 
	"DECHALLENGE" NUMBER, 
	"DECHALL_DATE" DATE, 
	"RECHALLENGE" NUMBER, 
	"RECHALL_START" DATE, 
	"RECHALL_STOP" DATE, 
	"RECHALL_OUTCOME" NUMBER, 
	"SORT_ID" NUMBER, 
	"B_WEIGHT_GRAMS" NUMBER, 
	"N_SIBLINGS" NUMBER, 
	"B_WEIGHT_OZS" NUMBER, 
	"FIRST_DOSE_PARTIAL" VARCHAR2(20 CHAR), 
	"LAST_DOSE_PARTIAL" VARCHAR2(20 CHAR), 
	"TAMPERING" NUMBER(4,0), 
	"CUMULATIVE_DOSE" NUMBER(22,7), 
	"CUMULATIVE_DOSE_UNIT" VARCHAR2(10 CHAR), 
	"DELETED" DATE, 
	"UD_TEXT_1" VARCHAR2(100 CHAR), 
	"UD_TEXT_2" VARCHAR2(100 CHAR), 
	"UD_TEXT_3" VARCHAR2(100 CHAR), 
	"UD_TEXT_4" VARCHAR2(100 CHAR), 
	"UD_TEXT_5" VARCHAR2(100 CHAR), 
	"UD_TEXT_6" VARCHAR2(100 CHAR), 
	"UD_TEXT_7" VARCHAR2(100 CHAR), 
	"UD_TEXT_8" VARCHAR2(100 CHAR), 
	"UD_TEXT_9" VARCHAR2(100 CHAR), 
	"UD_TEXT_10" VARCHAR2(100 CHAR), 
	"UD_TEXT_11" VARCHAR2(100 CHAR), 
	"UD_TEXT_12" VARCHAR2(100 CHAR), 
	"UD_DATE_1" DATE, 
	"UD_DATE_2" DATE, 
	"UD_DATE_3" DATE, 
	"UD_DATE_4" DATE, 
	"UD_DATE_5" DATE, 
	"UD_DATE_6" DATE, 
	"UD_DATE_7" DATE, 
	"UD_DATE_8" DATE, 
	"UD_DATE_9" DATE, 
	"UD_DATE_10" DATE, 
	"UD_DATE_11" DATE, 
	"UD_DATE_12" DATE, 
	"UD_NUMBER_1" NUMBER(30,10), 
	"UD_NUMBER_2" NUMBER(30,10), 
	"UD_NUMBER_3" NUMBER(30,10), 
	"UD_NUMBER_4" NUMBER(30,10), 
	"UD_NUMBER_5" NUMBER(30,10), 
	"UD_NUMBER_6" NUMBER(30,10), 
	"UD_NUMBER_7" NUMBER(30,10), 
	"UD_NUMBER_8" NUMBER(30,10), 
	"UD_NUMBER_9" NUMBER(30,10), 
	"UD_NUMBER_10" NUMBER(30,10), 
	"UD_NUMBER_11" NUMBER(30,10), 
	"UD_NUMBER_12" NUMBER(30,10), 
	"CUMULATIVE_DOSE_UNIT_ID" NUMBER, 
	"OBTAIN_DRUG_COUNTRY_ID" NUMBER, 
	"DRUG_AUTH_COUNTRY_ID" NUMBER, 
	"DURATION_SECONDS" NUMBER, 
	"LATENCY_SECONDS" NUMBER, 
	"DELAY_SECONDS" NUMBER, 
	"UD_TEXT_1_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_2_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_3_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_4_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_5_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_6_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_7_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_8_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_9_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_10_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_11_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_12_J" VARCHAR2(100 CHAR), 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_PROD_DRUGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_PROD_DRUGS" ON "MART_USER"."RM_CASE_PROD_DRUGS" ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_PROD_DRUGS
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_PROD_DRUGS" ON "MART_USER"."RM_CASE_PROD_DRUGS" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_PROD_DRUGS
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_PROD_DRUGS" ADD CONSTRAINT "PK_RM_CASE_PROD_DRUGS" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_PROD_DRUGS" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PROD_DRUGS" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PROD_DRUGS" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PROD_DRUGS" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_PRODUCT
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_PRODUCT" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"SEQ_NUM" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"DRUG_TYPE" NUMBER, 
	"PAT_EXPOSURE" NUMBER, 
	"MANUFACTURER_ID" NUMBER, 
	"PROTOCOL_FOLLOWED" NUMBER, 
	"FIRST_SUS_PROD" NUMBER, 
	"SELECTED_VIEW" NUMBER, 
	"SORT_ID" NUMBER, 
	"VIEWS_AVAILABLE" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"QC_SAFETY_DATE" DATE, 
	"QC_SENT_DATE" DATE, 
	"QC_RESULT_DATE" DATE, 
	"QC_CROSS_REFERENCE" VARCHAR2(16 CHAR), 
	"WHO_DRUG_CODE" VARCHAR2(45 CHAR), 
	"CO_DRUG_CODE" VARCHAR2(20 CHAR), 
	"PRODUCT_NAME" VARCHAR2(70 CHAR), 
	"GENERIC_NAME" CLOB, 
	"GENERIC_NAME_J" CLOB, 
	"UD_TEXT_1" VARCHAR2(100 CHAR), 
	"UD_TEXT_2" VARCHAR2(100 CHAR), 
	"UD_TEXT_3" VARCHAR2(100 CHAR), 
	"UD_TEXT_4" VARCHAR2(100 CHAR), 
	"UD_TEXT_5" VARCHAR2(100 CHAR), 
	"UD_TEXT_6" VARCHAR2(100 CHAR), 
	"UD_TEXT_7" VARCHAR2(100 CHAR), 
	"UD_TEXT_8" VARCHAR2(100 CHAR), 
	"UD_TEXT_9" VARCHAR2(100 CHAR), 
	"UD_TEXT_10" VARCHAR2(100 CHAR), 
	"UD_TEXT_11" VARCHAR2(100 CHAR), 
	"UD_TEXT_12" VARCHAR2(100 CHAR), 
	"UD_DATE_1" DATE, 
	"UD_DATE_2" DATE, 
	"UD_DATE_3" DATE, 
	"UD_DATE_4" DATE, 
	"UD_DATE_5" DATE, 
	"UD_DATE_6" DATE, 
	"UD_DATE_7" DATE, 
	"UD_DATE_8" DATE, 
	"UD_DATE_9" DATE, 
	"UD_DATE_10" DATE, 
	"UD_DATE_11" DATE, 
	"UD_DATE_12" DATE, 
	"UD_NUMBER_1" NUMBER(30,10), 
	"UD_NUMBER_2" NUMBER(30,10), 
	"UD_NUMBER_3" NUMBER(30,10), 
	"UD_NUMBER_4" NUMBER(30,10), 
	"UD_NUMBER_5" NUMBER(30,10), 
	"UD_NUMBER_6" NUMBER(30,10), 
	"UD_NUMBER_7" NUMBER(30,10), 
	"UD_NUMBER_8" NUMBER(30,10), 
	"UD_NUMBER_9" NUMBER(30,10), 
	"UD_NUMBER_10" NUMBER(30,10), 
	"UD_NUMBER_11" NUMBER(30,10), 
	"UD_NUMBER_12" NUMBER(30,10), 
	"INCLUDE_FREQUENCY" NUMBER, 
	"SDRUG_NOT_ADMIN" NUMBER, 
	"PROD_REPTD" VARCHAR2(255 CHAR), 
	"PROD_CODED" VARCHAR2(255 CHAR), 
	"PROD_SYN_ID" NUMBER, 
	"PROD_CODE_STATUS" NUMBER(3,0), 
	"DELETED" DATE, 
	"STUDY_PRODUCT_NUM" NUMBER(2,0), 
	"QC_QUANTITY" VARCHAR2(10 CHAR), 
	"QC_RETURN_DATE" DATE, 
	"QC_COMPLAINT_CAT_DATE" DATE, 
	"QC_ANALYSIS_CAT_DATE" DATE, 
	"QC_ANALYSIS_SUMMARY_DATE" DATE, 
	"PRIMARY_EVENT" NUMBER, 
	"MEDICINAL_PROD_ID" VARCHAR2(10 CHAR), 
	"FAMILY_ID" NUMBER, 
	"EXISTING_RPT_SEQ_MOD_FLG" NUMBER, 
	"DRUG_CODE_J" VARCHAR2(20 CHAR), 
	"DRUG_CODE_TYPE_J" NUMBER, 
	"PRODUCT_NAME_J" VARCHAR2(70 CHAR), 
	"PROD_CODED_J" VARCHAR2(255 CHAR), 
	"PROD_REPTD_J" VARCHAR2(255 CHAR), 
	"QC_CROSS_REFERENCE_J" VARCHAR2(16 CHAR), 
	"UD_TEXT_1_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_2_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_3_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_4_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_5_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_6_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_7_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_8_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_9_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_10_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_11_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_12_J" VARCHAR2(100 CHAR), 
	"DLP_REVISION_NUMBER" NUMBER, 
	"LAST_UPDATE_TIME" DATE, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"NOTES" CLOB, 
	"NOTES_J" CLOB, 
	"QC_ANALYSIS_CAT_TEXT" CLOB, 
	"QC_ANALYSIS_CAT_TEXT_J" CLOB, 
	"QC_ANAL_SUMMARY_TEXT" CLOB, 
	"QC_ANAL_SUMMARY_TEXT_J" CLOB, 
	"QC_RESULT" CLOB, 
	"QC_RESULT_J" CLOB, 
	"QC_COMMENT" CLOB, 
	"QC_COMMENT_J" CLOB, 
	"QC_COMPLAINT_CAT_TEXT" CLOB, 
	"QC_COMPLAINT_CAT_TEXT_J" CLOB, 
	"VAERS_BLOCK_ID" NUMBER, 
	"PROD_LIC_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" 
 LOB ("GENERIC_NAME") STORE AS BASICFILE "RCP_GEN_NAME_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("GENERIC_NAME_J") STORE AS BASICFILE "RCP_GEN_NAME_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("NOTES") STORE AS BASICFILE "RCP_NOTES_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("NOTES_J") STORE AS BASICFILE "RCP_NOTES_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("QC_ANALYSIS_CAT_TEXT") STORE AS BASICFILE "RCP_QC_ANAL_CAT_TEXT_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("QC_ANALYSIS_CAT_TEXT_J") STORE AS BASICFILE "RCP_QC_ANAL_CAT_TEXT_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("QC_ANAL_SUMMARY_TEXT") STORE AS BASICFILE "RCP_QC_ANAL_SUM_TEXT_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("QC_ANAL_SUMMARY_TEXT_J") STORE AS BASICFILE "RCP_QC_ANAL_SUM_TEXT_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("QC_RESULT") STORE AS BASICFILE "RCP_QC_RESULT_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("QC_RESULT_J") STORE AS BASICFILE "RCP_QC_RESULT_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("QC_COMMENT") STORE AS BASICFILE "RCP_QC_COMMENT_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("QC_COMMENT_J") STORE AS BASICFILE "RCP_QC_COMMENT_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("QC_COMPLAINT_CAT_TEXT") STORE AS BASICFILE "RCP_QC_COMP_CAT_TEXT_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("QC_COMPLAINT_CAT_TEXT_J") STORE AS BASICFILE "RCP_QC_COMP_CAT_TXT_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_PRODUCT" ON "MART_USER"."RM_CASE_PRODUCT" ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_PRODUCT
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_PRODUCT" ON "MART_USER"."RM_CASE_PRODUCT" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_PRODUCT
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_PRODUCT" ADD CONSTRAINT "PK_RM_CASE_PRODUCT" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_PRODUCT" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PRODUCT" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PRODUCT" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PRODUCT" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_REPORTERS
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_REPORTERS" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"SEQ_NUM" NUMBER, 
	"MEDIA_ID" NUMBER, 
	"OCCUPATION_ID" NUMBER, 
	"HCP_FLAG" NUMBER, 
	"PRIMARY_CONTACT" NUMBER, 
	"CORR_CONTACT" NUMBER, 
	"REPORTER_TYPE" NUMBER, 
	"INTERMEDIARY_ID" NUMBER, 
	"RPT_SENT" NUMBER, 
	"SORT_ID" NUMBER, 
	"CONFIDENTIAL" NUMBER(1,0), 
	"COUNTRY_ID" NUMBER, 
	"SUFFIX" VARCHAR2(15 CHAR), 
	"MIDDLE_NAME" VARCHAR2(15 CHAR), 
	"PREFIX" VARCHAR2(50 CHAR), 
	"FIRST_NAME" VARCHAR2(35 CHAR), 
	"LAST_NAME" VARCHAR2(50 CHAR), 
	"REPORTER_ID" VARCHAR2(20 CHAR), 
	"INSTITUTION" VARCHAR2(60 CHAR), 
	"DEPARTMENT" VARCHAR2(60 CHAR), 
	"CITY" VARCHAR2(35 CHAR), 
	"STATE" VARCHAR2(40 CHAR), 
	"POSTCODE" VARCHAR2(15 CHAR), 
	"COUNTRY" VARCHAR2(50 CHAR), 
	"PHONE" VARCHAR2(20 CHAR), 
	"ALTPHONE" VARCHAR2(20 CHAR), 
	"FAX" VARCHAR2(50 CHAR), 
	"REPORTER_REF" VARCHAR2(20 CHAR), 
	"EMAIL" VARCHAR2(100 CHAR), 
	"ADDRESS" VARCHAR2(120 CHAR), 
	"SUFFIX_J" VARCHAR2(15 CHAR), 
	"ADDRESS_J" VARCHAR2(120 CHAR), 
	"CITY_J" VARCHAR2(35 CHAR), 
	"DEPARTMENT_J" VARCHAR2(60 CHAR), 
	"FIRST_NAME_J" VARCHAR2(35 CHAR), 
	"INSTITUTION_J" VARCHAR2(60 CHAR), 
	"LAST_NAME_J" VARCHAR2(50 CHAR), 
	"MIDDLE_NAME_J" VARCHAR2(15 CHAR), 
	"PREFIX_J" VARCHAR2(50 CHAR), 
	"STATE_J" VARCHAR2(40 CHAR), 
	"DELETED" DATE, 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"NOTES" CLOB, 
	"NOTES_J" CLOB, 
	"INSTITUTION_ID" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" 
 LOB ("NOTES") STORE AS BASICFILE "RCR_NOTES_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("NOTES_J") STORE AS BASICFILE "RCR_NOTES_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_REPORTERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_REPORTERS" ON "MART_USER"."RM_CASE_REPORTERS" ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_REPORTERS
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_REPORTERS" ON "MART_USER"."RM_CASE_REPORTERS" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_REPORTERS
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_REPORTERS" ADD CONSTRAINT "PK_RM_CASE_REPORTERS" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_REPORTERS" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_REPORTERS" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_REPORTERS" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_REPORTERS" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_STUDY
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_STUDY" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"STUDY_KEY" NUMBER, 
	"STUDY_NUM" VARCHAR2(35 CHAR), 
	"STUDY_TYPE" NUMBER, 
	"CENTER_ID" NUMBER, 
	"CENTER_NAME" VARCHAR2(40 CHAR), 
	"PROTOCOL_ID" NUMBER, 
	"PROTOCOL_NUM" VARCHAR2(40 CHAR), 
	"OTHER_ID" VARCHAR2(20 CHAR), 
	"CODE_BROKEN" NUMBER, 
	"BROKEN_BY" NUMBER, 
	"BROKEN_DATE" DATE, 
	"REASON" VARCHAR2(100 CHAR), 
	"WEEK" VARCHAR2(5 CHAR), 
	"VISIT" VARCHAR2(5 CHAR), 
	"DELETED" DATE, 
	"PRODUCT_COUNT" NUMBER(2,0), 
	"CLASSIFICATION_ID" NUMBER, 
	"BLIND_NAME" VARCHAR2(70 CHAR), 
	"STUDY_DESC" CLOB, 
	"STUDY_DESC_J" CLOB, 
	"BLIND_NAME_J" VARCHAR2(70 CHAR), 
	"CENTER_NAME_J" VARCHAR2(40 CHAR), 
	"CLIN_COMPOUND_NUM_J" VARCHAR2(70 CHAR), 
	"PROTOCOL_NUM_J" VARCHAR2(40 CHAR), 
	"STUDY_NUM_J" VARCHAR2(35 CHAR), 
	"DEV_PHASE_ID" NUMBER, 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"COHORT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" 
 LOB ("STUDY_DESC") STORE AS BASICFILE "RCS_STUDY_DESC_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("STUDY_DESC_J") STORE AS BASICFILE "RCS_STUDY_DESC_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_STUDY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_STUDY" ON "MART_USER"."RM_CASE_STUDY" ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_STUDY
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_STUDY" ON "MART_USER"."RM_CASE_STUDY" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_STUDY
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_STUDY" ADD CONSTRAINT "PK_RM_CASE_STUDY" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_STUDY" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_STUDY" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_STUDY" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_STUDY" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_LM_CASE_CLASSIFICATION
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_LM_CASE_CLASSIFICATION" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CLASSIFICATION_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(30 CHAR), 
	"PROTECTED" NUMBER, 
	"DISPLAY" NUMBER, 
	"DESCRIPTION_J" VARCHAR2(30 CHAR), 
	"DELETED" DATE, 
	"E2B_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_LM_CASE_CLASSIFICATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_LM_CASE_CLASSIFICATION" ON "MART_USER"."RM_LM_CASE_CLASSIFICATION" ("ENTERPRISE_ID", "CLASSIFICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_LM_CASE_CLASSIFICATION
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_LM_CASE_CLASSIFICATION" ADD CONSTRAINT "PK_RM_LM_CASE_CLASSIFICATION" PRIMARY KEY ("ENTERPRISE_ID", "CLASSIFICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_LM_CASE_CLASSIFICATION" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_LM_CASE_CLASSIFICATION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_LM_CAUSALITY
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_LM_CAUSALITY" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CAUSALITY_ID" NUMBER, 
	"CAUSALITY" VARCHAR2(35 CHAR), 
	"REPORTABILITY" NUMBER, 
	"PROTECTED" NUMBER, 
	"DISPLAY" NUMBER, 
	"CAUSALITY_J" VARCHAR2(35 CHAR), 
	"DELETED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_LM_CAUSALITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_LM_CAUSALITY" ON "MART_USER"."RM_LM_CAUSALITY" ("ENTERPRISE_ID", "CAUSALITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_LM_CAUSALITY
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_LM_CAUSALITY" ADD CONSTRAINT "PK_RM_LM_CAUSALITY" PRIMARY KEY ("ENTERPRISE_ID", "CAUSALITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_LM_CAUSALITY" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_LM_CAUSALITY" MODIFY ("CAUSALITY" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_LM_COUNTRIES
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_LM_COUNTRIES" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"COUNTRY_ID" NUMBER, 
	"COUNTRY" VARCHAR2(50 CHAR), 
	"A2" VARCHAR2(2 CHAR), 
	"A3" VARCHAR2(3 CHAR), 
	"NUM" NUMBER, 
	"PROTECTED" NUMBER, 
	"DELETED" DATE, 
	"COUNTRY_GROUP_ID" NUMBER, 
	"COUNTRY_GROUP" VARCHAR2(50 CHAR), 
	"COUNTRY_J" VARCHAR2(50 CHAR), 
	"GROUP_2_COUNTRY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_LM_COUNTRIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_LM_COUNTRIES" ON "MART_USER"."RM_LM_COUNTRIES" ("ENTERPRISE_ID", "COUNTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_LM_COUNTRIES
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_LM_COUNTRIES" ADD CONSTRAINT "PK_RM_LM_COUNTRIES" PRIMARY KEY ("ENTERPRISE_ID", "COUNTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_LM_COUNTRIES" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_LM_COUNTRIES" MODIFY ("COUNTRY" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_LM_PRODUCT
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_LM_PRODUCT" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"PRODUCT_ID" NUMBER, 
	"PROD_NAME" VARCHAR2(70 CHAR), 
	"FAMILY_ID" NUMBER, 
	"FORMULATION_ID" NUMBER, 
	"MANUFACTURER_ID" NUMBER, 
	"CONCENTRATION" VARCHAR2(10 CHAR), 
	"CONC_UNIT_ID" NUMBER, 
	"INDICATION_ID" VARCHAR2(50 CHAR), 
	"CODE_DICT" NUMBER, 
	"INDICATION_TEXT" VARCHAR2(250 CHAR), 
	"INTL_BIRTH_DATE" DATE, 
	"MODEL_NO" VARCHAR2(20 CHAR), 
	"DRL_ID" VARCHAR2(45 CHAR), 
	"DRUG_CODE" VARCHAR2(20 CHAR), 
	"DELETED" DATE, 
	"PROD_GENERIC_NAME" CLOB, 
	"PROD_GENERIC_NAME_J" CLOB, 
	"IND_LLT_CODE" VARCHAR2(50 CHAR), 
	"IND_LLT" VARCHAR2(250 CHAR), 
	"IND_HLT_CODE" VARCHAR2(50 CHAR), 
	"IND_HLT" VARCHAR2(250 CHAR), 
	"IND_HLGT_CODE" VARCHAR2(50 CHAR), 
	"IND_HLGT" VARCHAR2(250 CHAR), 
	"IND_SOC_CODE" VARCHAR2(50 CHAR), 
	"IND_SOC" VARCHAR2(250 CHAR), 
	"IND_SYN_CODE" NUMBER, 
	"IND_CODE_STATUS" NUMBER, 
	"MEDICINAL_PROD_ID" VARCHAR2(10 CHAR), 
	"PROD_NAME_ABBRV" VARCHAR2(5 CHAR), 
	"DEVICE_CODE" VARCHAR2(50 CHAR), 
	"PSUR_GROUP_NAME" VARCHAR2(50 CHAR), 
	"COMMENTS" VARCHAR2(1000 CHAR), 
	"IND_CODED" VARCHAR2(250 CHAR), 
	"IND_REPTD" VARCHAR2(250 CHAR), 
	"DRL_ID_J" VARCHAR2(45 CHAR), 
	"DRUG_CODE_J" VARCHAR2(20 CHAR), 
	"DRUG_CODE_TYPE_J" NUMBER, 
	"INDICATION_TEXT_J" VARCHAR2(250 CHAR), 
	"IND_CODE_STATUS_J" NUMBER, 
	"IND_HLGT_J" VARCHAR2(250 CHAR), 
	"IND_HLT_J" VARCHAR2(250 CHAR), 
	"IND_LLT_CODE_J" VARCHAR2(50 CHAR), 
	"IND_LLT_J" VARCHAR2(250 CHAR), 
	"IND_SOC_J" VARCHAR2(250 CHAR), 
	"PROD_NAME_J" VARCHAR2(70 CHAR), 
	"IND_SYN_CODE_J" NUMBER, 
	"IND_CODED_J" VARCHAR2(250 CHAR), 
	"IND_REPTD_J" VARCHAR2(250 CHAR), 
	"DEV_INTL_BIRTH_DATE" DATE, 
	"COMMENTS_J" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" 
 LOB ("PROD_GENERIC_NAME") STORE AS BASICFILE "RLP_PROD_GENERIC_NAME_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PROD_GENERIC_NAME_J") STORE AS BASICFILE "RLP_PROD_GEN_NAME_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_RM_LM_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_LM_PRODUCT" ON "MART_USER"."RM_LM_PRODUCT" ("ENTERPRISE_ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_LM_PRODUCT
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_LM_PRODUCT" ADD CONSTRAINT "PK_RM_LM_PRODUCT" PRIMARY KEY ("ENTERPRISE_ID", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_LM_PRODUCT" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_LM_PRODUCT_FAMILY
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_LM_PRODUCT_FAMILY" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"FAMILY_ID" NUMBER, 
	"NAME" VARCHAR2(40 CHAR), 
	"PRIMARY_VIEW" NUMBER, 
	"DELETED" DATE, 
	"PRODUCT_GROUP_ID" NUMBER, 
	"COMMENTS" VARCHAR2(1000 CHAR), 
	"SEARCH_EQUATION_NUMBER" VARCHAR2(10 CHAR), 
	"NAME_J" VARCHAR2(40 CHAR), 
	"COMMENTS_J" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_LM_PRODUCT_FAMILY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_LM_PRODUCT_FAMILY" ON "MART_USER"."RM_LM_PRODUCT_FAMILY" ("ENTERPRISE_ID", "FAMILY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_LM_PRODUCT_FAMILY
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_LM_PRODUCT_FAMILY" ADD CONSTRAINT "PK_RM_LM_PRODUCT_FAMILY" PRIMARY KEY ("ENTERPRISE_ID", "FAMILY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_LM_PRODUCT_FAMILY" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_LM_REPORT_TYPE
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_LM_REPORT_TYPE" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"RPT_TYPE_ID" NUMBER, 
	"REPORT_TYPE" VARCHAR2(30 CHAR), 
	"PROTECTED" NUMBER, 
	"DISPLAY" NUMBER, 
	"INCL_LIT" NUMBER, 
	"INCL_TRIAL" NUMBER, 
	"E2B_CODE" NUMBER, 
	"ABRV" VARCHAR2(3 CHAR), 
	"INVESTIGATIONAL" NUMBER, 
	"REPORT_TYPE_J" VARCHAR2(30 CHAR), 
	"DELETED" DATE, 
	"INCL_RESEARCH" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_LM_REPORT_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_LM_REPORT_TYPE" ON "MART_USER"."RM_LM_REPORT_TYPE" ("ENTERPRISE_ID", "RPT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_LM_REPORT_TYPE
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_LM_REPORT_TYPE" ADD CONSTRAINT "PK_RM_LM_REPORT_TYPE" PRIMARY KEY ("ENTERPRISE_ID", "RPT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_LM_REPORT_TYPE" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_LM_REPORT_TYPE" MODIFY ("REPORT_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_LM_REPORT_TYPE" MODIFY ("INCL_RESEARCH" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_MEDDRA_SMQ_CONTENT
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" 
   (	"GLOBAL_DICT_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','meddra_global_dict_id'), 
	"SMQ_CODE" NUMBER, 
	"TERM_CODE" NUMBER, 
	"TERM_LEVEL" NUMBER, 
	"TERM_SCOPE" NUMBER, 
	"TERM_CATEGORY" VARCHAR2(1 CHAR), 
	"TERM_WEIGHT" NUMBER, 
	"TERM_STATUS" VARCHAR2(1 CHAR), 
	"TERM_ADDITION_VERSION" VARCHAR2(5 CHAR), 
	"TERM_LAST_MODIFIED_VERSION" VARCHAR2(5 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_MEDDRA_SMQ_CONTENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_MEDDRA_SMQ_CONTENT" ON "MART_USER"."RM_MEDDRA_SMQ_CONTENT" ("GLOBAL_DICT_ID", "SMQ_CODE", "TERM_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_MEDDRA_SMQ_CONTENT
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" ADD CONSTRAINT "PK_RM_MEDDRA_SMQ_CONTENT" PRIMARY KEY ("GLOBAL_DICT_ID", "SMQ_CODE", "TERM_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("GLOBAL_DICT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_LEVEL" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_SCOPE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_CATEGORY" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_WEIGHT" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_ADDITION_VERSION" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_LAST_MODIFIED_VERSION" NOT NULL ENABLE);
--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_MEDDRA_SMQ_LIST
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_MEDDRA_SMQ_LIST" 
   (	"GLOBAL_DICT_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','meddra_global_dict_id'), 
	"SMQ_CODE" NUMBER, 
	"SMQ_NAME" VARCHAR2(100 CHAR), 
	"SMQ_LEVEL" NUMBER, 
	"SMQ_DESCRIPTION" VARCHAR2(3000 CHAR), 
	"SMQ_SOURCE" VARCHAR2(2000 CHAR), 
	"SMQ_NOTE" VARCHAR2(2000 CHAR), 
	"MEDDRA_VERSION" VARCHAR2(5 CHAR), 
	"STATUS" VARCHAR2(1 CHAR), 
	"SMQ_ALGORITHM" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_MEDDRA_SMQ_LIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_MEDDRA_SMQ_LIST" ON "MART_USER"."RM_MEDDRA_SMQ_LIST" ("GLOBAL_DICT_ID", "SMQ_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_MEDDRA_SMQ_LIST
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_LIST" ADD CONSTRAINT "PK_RM_MEDDRA_SMQ_LIST" PRIMARY KEY ("GLOBAL_DICT_ID", "SMQ_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_LIST" MODIFY ("GLOBAL_DICT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_LIST" MODIFY ("SMQ_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_LIST" MODIFY ("SMQ_LEVEL" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_LIST" MODIFY ("MEDDRA_VERSION" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_LIST" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_LIST" MODIFY ("SMQ_ALGORITHM" NOT NULL ENABLE);
