SELECT
    a.CASE_ID, a.BLIND_NAME, a.CENTER_ID, a.CLASSIFICATION_ID, a.CODE_BROKEN,
    a.DEV_PHASE_ID, a.OTHER_ID, a.STUDY_DESC, a.STUDY_KEY, a.STUDY_NUM, b.VERSION_NUM,
    b.EFFECTIVE_START_DATE, b.EFFECTIVE_END_DATE, a.ENTERPRISE_ID
FROM
    ArgusMart.RM_CASE_STUDY AS a, ArgusMart.CASE_VERSION_TABLE AS b
WHERE
    (a.CASE_ID = b.CASE_ID) AND 
    (a.ENTERPRISE_ID = b.ENTERPRISE_ID) AND 
    (a.DELETED_FLAG = convert(0, bigdecimal)) AND 
    (convert(a.EFFECTIVE_START_DATE, timestamp) <= b.EFFECTIVE_START_DATE) AND 
    (convert(a.EFFECTIVE_END_DATE, timestamp) > b.EFFECTIVE_START_DATE)

--------------------

