SELECT
    A.ENTERPRISE_ID, A.CASE_ID, A.SEQ_NUM, A.CLASSIFICATION_ID, A.DELETED,
    B.VERSION_NUM, B.EFFECTIVE_START_DATE, B.EFFECTIVE_END_DATE
FROM
    ArgusMart.RM_CASE_CLASSIFICATIONS AS A, ArgusMartView.CASE_VERSION_TABLE AS B
WHERE
    (A.CASE_ID = B.CASE_ID) AND 
    (A.EFFECTIVE_START_DATE <= B.EFFECTIVE_START_DATE) AND 
    (A.EFFECTIVE_END_DATE > B.EFFECTIVE_START_DATE)

--------------------

