SELECT
    ArgusMart.RM_LM_PRODUCT_FAMILY.ENTERPRISE_ID,
    ArgusMart.RM_LM_PRODUCT_FAMILY.FAMILY_ID, ArgusMart.RM_LM_PRODUCT_FAMILY.NAME,
    ArgusMart.RM_LM_PRODUCT_FAMILY.PRIMARY_VIEW,
    ArgusMart.RM_LM_PRODUCT_FAMILY.PRODUCT_GROUP_ID,
    ArgusMart.RM_LM_PRODUCT_FAMILY.DELETED, ArgusMart.RM_LM_PRODUCT_FAMILY.NAME_J
FROM
    ArgusMart.RM_LM_PRODUCT_FAMILY

--------------------

