(ns pg-demo.table-defs
  (:require [clojure.java.jdbc      :as jdbc]
            [java-jdbc.ddl          :as ddl]
            [java-jdbc.sql          :as jdbc-sql]
  )
  (:gen-class))

; A map from table name (string) -> table creation sql (string)
(def table-name->creation-sql 
  (into (sorted-map) [
    { "rm_case_master"
          "CREATE TABLE rm_case_master (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              CASE_NUM varchar(20),
              REV numeric,
              WORKFLOW_SEQ_NUM numeric,
              LAST_WORKFLOW_SEQ_NUM numeric,
              CREATE_TIME timestamp,
              INIT_REPT_DATE timestamp,
              USER_ID numeric,
              LAST_UPDATE_TIME timestamp,
              LAST_UPDATE_USER_ID numeric,
              REQUIRES_FOLLOWUP numeric,
              FOLLOWUP_DATE timestamp,
              OWNER_ID numeric,
              STATE_ID numeric,
              COUNTRY_ID numeric,
              LANG_ID numeric,
              PRIORITY numeric,
              SITE_ID numeric,
              SERIOUSNESS numeric,
              RPT_TYPE_ID numeric,
              LAST_STATE_ID numeric,
              ASSESSMENT_NEEDED numeric,
              PRIORITY_OVERRIDE numeric(1),
              SID varchar(128),
              SAFETY_DATE timestamp,
              NORMAL_TIME timestamp,
              MAX_TIME timestamp,
              REPORT_SCHEDULING numeric,
              PRIORITY_ASSESSMENT numeric,
              CLOSE_USER_ID numeric,
              CLOSE_DATE timestamp,
              CLOSE_NOTES varchar(200),
              DATE_LOCKED timestamp,
              UD_TEXT_1 varchar(100),
              UD_TEXT_2 varchar(100),
              UD_TEXT_3 varchar(100),
              UD_TEXT_4 varchar(100),
              UD_TEXT_5 varchar(100),
              UD_TEXT_6 varchar(100),
              UD_TEXT_7 varchar(100),
              UD_TEXT_8 varchar(100),
              UD_TEXT_9 varchar(100),
              UD_TEXT_10 varchar(100),
              UD_TEXT_11 varchar(100),
              UD_TEXT_12 varchar(100),
              UD_DATE_1 timestamp,
              UD_DATE_2 timestamp,
              UD_DATE_3 timestamp,
              UD_DATE_4 timestamp,
              UD_DATE_5 timestamp,
              UD_DATE_6 timestamp,
              UD_DATE_7 timestamp,
              UD_DATE_8 timestamp,
              UD_DATE_9 timestamp,
              UD_DATE_10 timestamp,
              UD_DATE_11 timestamp,
              UD_DATE_12 timestamp,
              UD_NUMBER_1 numeric(30,10),
              UD_NUMBER_2 numeric(30,10),
              UD_NUMBER_3 numeric(30,10),
              UD_NUMBER_4 numeric(30,10),
              UD_NUMBER_5 numeric(30,10),
              UD_NUMBER_6 numeric(30,10),
              UD_NUMBER_7 numeric(30,10),
              UD_NUMBER_8 numeric(30,10),
              UD_NUMBER_9 numeric(30,10),
              UD_NUMBER_10 numeric(30,10),
              UD_NUMBER_11 numeric(30,10),
              UD_NUMBER_12 numeric(30,10),
              DELETED timestamp,
              DUE_SOON timestamp,
              GLOBAL_NUM varchar(20),
              PRIORITY_DATE_ASSESSED timestamp,
              LAM_ASSESS_DONE numeric(1),
              E2B_WW_NUMBER varchar(100),
              WORKLIST_OWNER_ID numeric,
              SUSAR numeric,
              LAST_UPDATE_EVENT timestamp,
              INITIAL_JUSTIFICATION varchar(1000),
              FORCE_SOON timestamp,
              DUE_SOON_J timestamp,
              FOLLOWUP_DATE_J timestamp,
              INIT_REPT_DATE_J timestamp,
              JUST_INIT_REPT_DATE_J varchar(1000),
              UD_TEXT_1_J varchar(100),
              UD_TEXT_2_J varchar(100),
              UD_TEXT_3_J varchar(100),
              UD_TEXT_4_J varchar(100),
              UD_TEXT_5_J varchar(100),
              UD_TEXT_6_J varchar(100),
              UD_TEXT_7_J varchar(100),
              UD_TEXT_8_J varchar(100),
              UD_TEXT_9_J varchar(100),
              UD_TEXT_10_J varchar(100),
              UD_TEXT_11_J varchar(100),
              UD_TEXT_12_J varchar(100),
              INITIAL_JUSTIFICATION_J varchar(1000),
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,DLP_REVISION_NUMBER) 
          );" }

    { "rm_case_actions"
          "CREATE TABLE rm_case_actions (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              USER_ID numeric,
              DATE_OPEN timestamp,
              DATE_DUE timestamp,
              DATE_DONE timestamp,
              DESCRIPTION varchar(1000),
              SORT_ID numeric,
              CODE numeric,
              GROUP_ID numeric,
              SYSTEM_CREATED numeric,
              ACTION_STATUS numeric,
              DESCRIPTION_J varchar(1000),
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              SENT_IN_LTR numeric,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          );" }

    { "rm_case_afssaps"
          "CREATE TABLE rm_case_afssaps (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              PROCEED_WO_CHANGE numeric(1),
              PROCEED_W_CHANGE numeric(1),
              TERM_STUDY_PROTOCOL numeric(1),
              TERM_PRODUCT_DEV numeric(1),
              OTHER numeric(1),
              OTHER_DESC varchar(50),
              FUTURE_ACTIONS text,
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              DELETED_FLAG numeric(1) NOT NULL,
              REVISION_DELETE_FLAG numeric,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          );" }

    { "rm_case_all_locked_rev"
          "CREATE TABLE rm_case_all_locked_rev (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              DLP_REVISION_NUMBER numeric NOT NULL,
              DATE_LOCKED timestamp,
              USER_LOCKED numeric(1),
              CASE_DELETED numeric(1),
              CLOSE_DATE timestamp,
              VALIDSTART timestamp,
              VALIDEND timestamp,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,DLP_REVISION_NUMBER)
          );" }

    { "rm_case_assess"
          "CREATE TABLE rm_case_assess (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              TEMPLATE_ID numeric,
              LISTEDNESS numeric,
              UPDATED timestamp,
              OUTCOME numeric,
              COMMENT_ID numeric,
              COMP_COMMENT_ID numeric,
              SERIOUSNESS numeric,
              SERIOUS_NOTES varchar(1000),
              AGENT_SUSPECT numeric,
              AGENT_NOTES varchar(1000),
              LISTEDNESS_NOTES varchar(1000),
              BFARM_CAUSALITY numeric(10),
              BFARM_MANUAL_TEXT text,
              COMPANY_DIAGNOSIS varchar(250),
              COMPANY_DIAGNOSIS_NOTES varchar(1000),
              DIAGNOSIS_DICT_ID numeric,
              DIAGNOSIS_PREF_CODE varchar(30),
              DIAGNOSIS_INC_CODE varchar(30),
              DIAGNOSIS_INC_TERM varchar(250),
              DIAGNOSIS_HLGT_CODE varchar(30),
              DIAGNOSIS_HLGT varchar(250),
              DIAGNOSIS_HLT_CODE varchar(30),
              DIAGNOSIS_HLT varchar(250),
              DIAGNOSIS_SOC_CODE varchar(30),
              DIAGNOSIS_BODY_SYS varchar(250),
              UD_TEXT_1 varchar(100),
              UD_TEXT_2 varchar(100),
              UD_TEXT_3 varchar(100),
              UD_TEXT_4 varchar(100),
              UD_TEXT_5 varchar(100),
              UD_TEXT_6 varchar(100),
              UD_TEXT_7 varchar(100),
              UD_TEXT_8 varchar(100),
              UD_TEXT_9 varchar(100),
              UD_TEXT_10 varchar(100),
              UD_TEXT_11 varchar(100),
              UD_TEXT_12 varchar(100),
              UD_DATE_1 timestamp,
              UD_DATE_2 timestamp,
              UD_DATE_3 timestamp,
              UD_DATE_4 timestamp,
              UD_DATE_5 timestamp,
              UD_DATE_6 timestamp,
              UD_DATE_7 timestamp,
              UD_DATE_8 timestamp,
              UD_DATE_9 timestamp,
              UD_DATE_10 timestamp,
              UD_DATE_11 timestamp,
              UD_DATE_12 timestamp,
              UD_NUMBER_1 numeric(30,10),
              UD_NUMBER_2 numeric(30,10),
              UD_NUMBER_3 numeric(30,10),
              UD_NUMBER_4 numeric(30,10),
              UD_NUMBER_5 numeric(30,10),
              UD_NUMBER_6 numeric(30,10),
              UD_NUMBER_7 numeric(30,10),
              UD_NUMBER_8 numeric(30,10),
              UD_NUMBER_9 numeric(30,10),
              UD_NUMBER_10 numeric(30,10),
              UD_NUMBER_11 numeric(30,10),
              UD_NUMBER_12 numeric(30,10),
              EVALUATION text,
              EVALUATION_J text,
              CO_SUSPECT_COUNT numeric(3),
              EVENT_SYNOPSIS varchar(5),
              EVENT_PRIMARY varchar(400),
              DIAGNOSIS_REPTD varchar(255),
              DIAGNOSIS_CODED varchar(255),
              DIAGNOSIS_SYN_CODE numeric,
              DIAGNOSIS_CODE_STATUS numeric(3),
              EVENT_PRIMARY_J varchar(400),
              AGENT_NOTES_J varchar(1000),
              COMPANY_DIAGNOSIS_J varchar(250),
              COMPANY_DIAGNOSIS_NOTES_J varchar(1000),
              DIAGNOSIS_BODY_SYS_J varchar(250),
              DIAGNOSIS_CODED_J varchar(255),
              DIAGNOSIS_CODE_STATUS_J numeric,
              DIAGNOSIS_HLGT_J varchar(250),
              DIAGNOSIS_HLT_J varchar(250),
              DIAGNOSIS_INC_CODE_J varchar(30),
              DIAGNOSIS_INC_TERM_J varchar(250),
              DIAGNOSIS_REPTD_J varchar(255),
              LISTEDNESS_NOTES_J varchar(1000),
              SERIOUS_NOTES_J varchar(1000),
              UD_TEXT_1_J varchar(100),
              UD_TEXT_2_J varchar(100),
              UD_TEXT_3_J varchar(100),
              UD_TEXT_4_J varchar(100),
              UD_TEXT_5_J varchar(100),
              UD_TEXT_6_J varchar(100),
              UD_TEXT_7_J varchar(100),
              UD_TEXT_8_J varchar(100),
              UD_TEXT_9_J varchar(100),
              UD_TEXT_10_J varchar(100),
              UD_TEXT_11_J varchar(100),
              UD_TEXT_12_J varchar(100),
              DIAGNOSIS_SYN_CODE_J numeric,
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_bfarm_data"
          "CREATE TABLE rm_case_bfarm_data (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              MED_STATUS_ID numeric NOT NULL,
              MED_STATUS numeric,
              OTHER_TEXT varchar(20),
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              DELETED_FLAG numeric(1) NOT NULL,
              REVISION_DELETE_FLAG numeric,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,MED_STATUS_ID,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_classifications"
          "CREATE TABLE rm_case_classifications (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              CLASSIFICATION_ID numeric,
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_comments"
          "CREATE TABLE rm_case_comments (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              COMMENT_TXT text,
              COMMENT_TXT_J text,
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_company_cmts"
          "CREATE TABLE rm_case_company_cmts (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              DELETED timestamp,
              COMMENT_TXT text,
              COMMENT_TXT_J text,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_contact_log"
          "CREATE TABLE rm_case_contact_log (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              CONTACT_DATE timestamp,
              CONTACT_TYPE numeric,
              DESCRIPTION varchar(1000),
              USER_ID numeric,
              DATE_SENT timestamp,
              SORT_ID numeric,
              CODE numeric,
              GROUP_ID numeric,
              LAM_ID numeric(10),
              LAM_CONTACT_LOG_ID numeric(10),
              DESCRIPTION_J varchar(1000),
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              DELETED_FLAG numeric(1) NOT NULL,
              REVISION_DELETE_FLAG numeric,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          );
          " }

    { "rm_case_death"
          "CREATE TABLE rm_case_death (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              DEATH_DATE timestamp,
              AUTOPSY numeric,
              DEATH_DATE_RES numeric,
              DEATH_DATE_PARTIAL varchar(20),
              DETERMINE_AUTOPSY varchar(250),
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_death_details"
          "CREATE TABLE rm_case_death_details (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              SORT_ID numeric,
              TERM_TYPE numeric,
              CAUSE_REPTD varchar(1000),
              CAUSE_CODED varchar(1000),
              CAUSE varchar(1000),
              CAUSE_CODE varchar(50),
              CAUSE_LLT varchar(250),
              CAUSE_LLT_CODE varchar(50),
              CAUSE_HLT varchar(250),
              CAUSE_HLT_CODE varchar(50),
              CAUSE_HLGT varchar(250),
              CAUSE_HLGT_CODE varchar(50),
              CAUSE_SOC varchar(250),
              CAUSE_SOC_CODE varchar(50),
              CAUSE_SYN_CODE numeric,
              CAUSE_DICT numeric,
              CAUSE_CODE_STATUS numeric(3),
              CAUSE_CODED_J varchar(1000),
              CAUSE_SOC_J varchar(250),
              CAUSE_CODE_STATUS_J numeric,
              CAUSE_HLGT_J varchar(250),
              CAUSE_HLT_J varchar(250),
              CAUSE_J varchar(1000),
              CAUSE_LLT_CODE_J varchar(50),
              CAUSE_LLT_J varchar(250),
              CAUSE_REPTD_J varchar(1000),
              CAUSE_SYN_CODE_J numeric,
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_device_prod_deliv"
          "CREATE TABLE rm_case_device_prod_deliv (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              PROD_SEQ_NUM numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              PROD_DELIV_SEQ numeric,
              DELETED timestamp,
              TYPE numeric,
              OTHER_MFG_PROD varchar(100),
              OTHER_MFG_PROD_J varchar(100),
              DLP_REVISION_NUMBER numeric NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              DELETED_FLAG numeric(1) NOT NULL,
              REVISION_DELETE_FLAG numeric,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,PROD_SEQ_NUM,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_dose_regimens"
          "CREATE TABLE rm_case_dose_regimens (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              LOG_NO numeric NOT NULL,
              START_DATETIME timestamp,
              START_DATETIME_RES numeric,
              STOP_DATETIME timestamp,
              STOP_DATETIME_RES numeric,
              ONGOING numeric,
              OFF_LABEL numeric,
              DOSE numeric(22,7),
              DOSE_UNIT_ID numeric,
              FREQ_ID numeric,
              ADMIN_ROUTE_ID numeric,
              DAILY_DOSE numeric(22,7),
              DAILY_DOSE_UNIT_ID numeric,
              EXP_DATE timestamp,
              EXP_DATE_RES numeric,
              TOTAL_REG_DOSE numeric(22,7),
              TOT_REG_DOSE_UNIT_ID numeric,
              SORT_ID numeric,
              PARENT_SEQ_NUM numeric,
              LOCATION_ID numeric,
              DOSE_NO numeric,
              PAR_ADMIN_ROUTE numeric,
              EXP_DATE_PARTIAL varchar(20),
              START_DATE_PARTIAL varchar(20),
              STOP_DATE_PARTIAL varchar(20),
              DOSE_DESCRIPTION varchar(100),
              PACKAGE_ID varchar(20),
              LOT_NO varchar(35),
              PACK_UNITS numeric,
              ACCIDENTAL_EXPOSURE numeric,
              DELETED timestamp,
              LOT_ID numeric,
              LOT_JUST varchar(1000),
              LOT_STATUS numeric(1),
              UD_TEXT_1 varchar(100),
              UD_TEXT_2 varchar(100),
              UD_TEXT_3 varchar(100),
              UD_TEXT_4 varchar(100),
              UD_TEXT_5 varchar(100),
              UD_TEXT_6 varchar(100),
              UD_TEXT_7 varchar(100),
              UD_TEXT_8 varchar(100),
              UD_TEXT_9 varchar(100),
              UD_TEXT_10 varchar(100),
              UD_TEXT_11 varchar(100),
              UD_TEXT_12 varchar(100),
              UD_DATE_1 timestamp,
              UD_DATE_2 timestamp,
              UD_DATE_3 timestamp,
              UD_DATE_4 timestamp,
              UD_DATE_5 timestamp,
              UD_DATE_6 timestamp,
              UD_DATE_7 timestamp,
              UD_DATE_8 timestamp,
              UD_DATE_9 timestamp,
              UD_DATE_10 timestamp,
              UD_DATE_11 timestamp,
              UD_DATE_12 timestamp,
              UD_NUMBER_1 numeric(30,10),
              UD_NUMBER_2 numeric(30,10),
              UD_NUMBER_3 numeric(30,10),
              UD_NUMBER_4 numeric(30,10),
              UD_NUMBER_5 numeric(30,10),
              UD_NUMBER_6 numeric(30,10),
              UD_NUMBER_7 numeric(30,10),
              UD_NUMBER_8 numeric(30,10),
              UD_NUMBER_9 numeric(30,10),
              UD_NUMBER_10 numeric(30,10),
              UD_NUMBER_11 numeric(30,10),
              UD_NUMBER_12 numeric(30,10),
              DURATION_SECONDS numeric,
              DOSE_DESCRIPTION_J varchar(100),
              UD_TEXT_1_J varchar(100),
              UD_TEXT_2_J varchar(100),
              UD_TEXT_3_J varchar(100),
              UD_TEXT_4_J varchar(100),
              UD_TEXT_5_J varchar(100),
              UD_TEXT_6_J varchar(100),
              UD_TEXT_7_J varchar(100),
              UD_TEXT_8_J varchar(100),
              UD_TEXT_9_J varchar(100),
              UD_TEXT_10_J varchar(100),
              UD_TEXT_11_J varchar(100),
              UD_TEXT_12_J varchar(100),
              LOT_JUST_J varchar(1000),
              DLP_REVISION_NUMBER numeric NOT NULL,
              LAST_UPDATE_TIME timestamp,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              VAERS_BLOCK_10 numeric,
              VAERS_BLOCK_14 numeric,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,LOG_NO,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_eu_device"
          "CREATE TABLE rm_case_eu_device (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              ACCESSORIES varchar(90),
              VERSION varchar(40),
              IDENTIFICATION varchar(90),
              PREVIOUSLY_REPORTED numeric,
              INCIDENT numeric,
              COUNTRY varchar(1000),
              EXPECTED_DATE timestamp,
              EXPECTED_DATE_RES numeric,
              EXPECTED_DATE_PARTIAL varchar(20),
              PROJECTED_TIMING text,
              PROJECTED_TIMING_FINAL text,
              CORRECTIVE_ACTION_FINAL text,
              INVESTIGATION_RESULT text,
              FURTHER_INVESTIGATION text,
              CURRENT_DEV_LOCATIONS text,
              COUNTRIES_OF_DISTRIBUTION text,
              DELETED timestamp,
              CORRECTIVE_ACTION text,
              DEVICE_PURCHASED varchar(120),
              ADDRESS varchar(120),
              DEVICE_STERILE numeric(1),
              IMPORTER_NAME varchar(100),
              IMPORTER_ADDRESS varchar(120),
              IMPORTER_POSTCODE varchar(15),
              IMPORTER_PHONE varchar(20),
              IMPORTER_FAX varchar(50),
              SEQ_NUM numeric NOT NULL,
              PROD_SEQ_NUM numeric,
              NCA_REF_NUM varchar(100),
              INDENTIF text,
              PATS_INVOLVED numeric,
              DEVS_INVOLVED numeric,
              USER_FAC_REF varchar(20),
              REMEDIAL_ACTION varchar(1000),
              DEV_USAGE numeric,
              OTHER varchar(15),
              UPDATE_TO_REPORT numeric(1),
              FINAL_REPORT numeric(1),
              PUBLIC_THREAT numeric,
              SIMILAR_INCIDENT_NUM numeric(3),
              MANUFACTURER_COMMENTS text,
              DLP_REVISION_NUMBER numeric NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              DELETED_FLAG numeric(1) NOT NULL,
              REVISION_DELETE_FLAG numeric,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_event"
          "CREATE TABLE rm_case_event (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              DESC_REPTD varchar(250),
              DESC_CODED varchar(255),
              DIAGNOSIS numeric,
              ONSET timestamp,
              ONSET_RES numeric,
              ONSET_DELAY varchar(40),
              STOP_DATE timestamp,
              STOP_DATE_RES numeric,
              DURATION varchar(40),
              ONSET_LATENCY varchar(40),
              EVT_INTENSITY_ID numeric,
              EVT_FREQ_ID numeric,
              TREATED numeric,
              STUDY_RELATED numeric,
              RECHALL_RELATED numeric,
              PROD_SEQ_NUM numeric,
              EVT_OUTCOME_ID numeric,
              RECEIPT_DATE timestamp,
              RPT_SERIOUS numeric,
              SC_DEATH numeric,
              SC_HOSP numeric,
              SC_CONG_ANOM numeric,
              SC_THREAT numeric,
              SC_DISABLE numeric,
              SC_INT_REQ numeric,
              SC_OTHER numeric,
              SC_OTHER_TEXT varchar(30),
              ART_CODE varchar(30),
              PREF_TERM varchar(250),
              INC_TERM varchar(250),
              BODY_SYS varchar(250),
              MED_SERIOUS numeric,
              PAST_HIST numeric,
              DICT_ID numeric,
              DICT_KEY varchar(20),
              CODE_STATUS numeric,
              SERIOUSNESS numeric,
              SORT_ID numeric,
              ONSET_DATE_PARTIAL varchar(20),
              STOP_DATE_PARTIAL varchar(20),
              EFFICACY numeric,
              DISEASE numeric,
              WITHDRAWAL numeric,
              HLGT varchar(250),
              HLT varchar(250),
              HLT_CODE varchar(30),
              HLGT_CODE varchar(30),
              SOC_CODE varchar(30),
              STUDY_DROPPED numeric(4),
              INC_CODE varchar(30),
              ONSET_MINUTES numeric,
              DELAY_MINUTES numeric,
              UD_TEXT_1 varchar(100),
              UD_TEXT_2 varchar(100),
              UD_TEXT_3 varchar(100),
              UD_TEXT_4 varchar(100),
              UD_TEXT_5 varchar(100),
              UD_TEXT_6 varchar(100),
              UD_TEXT_7 varchar(100),
              UD_TEXT_8 varchar(100),
              UD_TEXT_9 varchar(100),
              UD_TEXT_10 varchar(100),
              UD_TEXT_11 varchar(100),
              UD_TEXT_12 varchar(100),
              UD_DATE_1 timestamp,
              UD_DATE_2 timestamp,
              UD_DATE_3 timestamp,
              UD_DATE_4 timestamp,
              UD_DATE_5 timestamp,
              UD_DATE_6 timestamp,
              UD_DATE_7 timestamp,
              UD_DATE_8 timestamp,
              UD_DATE_9 timestamp,
              UD_DATE_10 timestamp,
              UD_DATE_11 timestamp,
              UD_DATE_12 timestamp,
              UD_NUMBER_1 numeric(30,10),
              UD_NUMBER_2 numeric(30,10),
              UD_NUMBER_3 numeric(30,10),
              UD_NUMBER_4 numeric(30,10),
              UD_NUMBER_5 numeric(30,10),
              UD_NUMBER_6 numeric(30,10),
              UD_NUMBER_7 numeric(30,10),
              UD_NUMBER_8 numeric(30,10),
              UD_NUMBER_9 numeric(30,10),
              UD_NUMBER_10 numeric(30,10),
              UD_NUMBER_11 numeric(30,10),
              UD_NUMBER_12 numeric(30,10),
              DETAILS text,
              DETAILS_J text,
              SYN_CODE numeric,
              DELETED timestamp,
              STUDY_RELATED_REPTD numeric(1),
              DURATION_UNIT_E2B numeric,
              ONSET_LATENCY_UNIT_E2B numeric,
              ONSET_DELAY_UNIT_E2B numeric,
              DURATION_SECONDS numeric,
              ONSET_LATENCY_SECONDS numeric,
              ONSET_DELAY_SECONDS numeric,
              BODY_SYS_J varchar(250),
              CODE_STATUS_J numeric,
              DESC_CODED_J varchar(255),
              DESC_REPTD_J varchar(250),
              HLGT_J varchar(250),
              HLT_J varchar(250),
              INC_CODE_J varchar(30),
              INC_TERM_J varchar(250),
              PREF_TERM_J varchar(250),
              SC_OTHER_TEXT_J varchar(30),
              REPORT_EXCLUSION numeric,
              REPORTABLE numeric,
              UD_TEXT_1_J varchar(100),
              UD_TEXT_2_J varchar(100),
              UD_TEXT_3_J varchar(100),
              UD_TEXT_4_J varchar(100),
              UD_TEXT_5_J varchar(100),
              UD_TEXT_6_J varchar(100),
              UD_TEXT_7_J varchar(100),
              UD_TEXT_8_J varchar(100),
              UD_TEXT_9_J varchar(100),
              UD_TEXT_10_J varchar(100),
              UD_TEXT_11_J varchar(100),
              UD_TEXT_12_J varchar(100),
              SYN_CODE_J numeric,
              INFECTION numeric,
              RPT_EXCLUDE_CMT varchar(1000),
              RPT_EXCLUDE_CMT_J varchar(1000),
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_event_assess"
          "CREATE TABLE rm_case_event_assess (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              EVENT_SEQ_NUM numeric NOT NULL,
              PROD_SEQ_NUM numeric NOT NULL,
              DATASHEET_ID numeric NOT NULL,
              LICENSE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              UPDATED timestamp,
              DET_LISTEDNESS_ID numeric,
              RPT_CAUSALITY_ID numeric,
              DET_CAUSALITY_ID numeric,
              LISTED_JUSTIFY varchar(1000),
              CAUSE_JUSTIFY varchar(1000),
              LAM_ASSESSED numeric(12),
              DELETED timestamp,
              CAUSALITY_ASSESSMENT varchar(50),
              CAUSALITY_SCORE numeric,
              SOURCE_ID numeric,
              PRT_CAUSALITY_ID numeric,
              CAUSE_JUSTIFY_J varchar(1000),
              LISTED_JUSTIFY_J varchar(1000),
              DLP_REVISION_NUMBER numeric NOT NULL,
              LAST_UPDATE_TIME timestamp,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,EVENT_SEQ_NUM,PROD_SEQ_NUM,DATASHEET_ID,LICENSE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_event_consequence"
          "CREATE TABLE rm_case_event_consequence (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              ED_SEQ_NUM numeric NOT NULL,
              EVT_CONSEQUENCE_ID numeric NOT NULL,
              CONSEQUENCE varchar(100),
              TERM varchar(250),
              CONSEQUENCE_J varchar(100),
              TERM_J varchar(250),
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              DELETED_FLAG numeric(1) NOT NULL,
              REVISION_DELETE_FLAG numeric,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_event_detail"
          "CREATE TABLE rm_case_event_detail (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              PROD_SEQ_NUM numeric NOT NULL,
              EVENT_SEQ_NUM numeric NOT NULL,
              ONSET_DELAY varchar(40),
              ONSET_DELAY_SECONDS numeric,
              ONSET_LATENCY varchar(40),
              ONSET_LATENCY_SECONDS numeric,
              TOTAL_DOSE numeric(22,7),
              TOTAL_DOSE_UNIT_ID numeric,
              MOST_IMPORTANT numeric,
              MORE_SPECIFIC numeric,
              ACT_TAKEN_ID numeric,
              OTHER_INFORMATION varchar(250),
              DECHALLENGE numeric,
              RECHALLENGE numeric,
              OTHER_INFORMATION_J varchar(250),
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_event_imputability"
          "CREATE TABLE rm_case_event_imputability (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              EVENT_SEQ_NUM numeric NOT NULL,
              AGENT_SEQ_NUM numeric NOT NULL,
              CHRONOLOGY varchar(4),
              SEMIOLOGY varchar(4),
              BIBLIOGRAPHY varchar(4),
              IMPUTABILITY varchar(4),
              DELETED timestamp,
              TIME_TO_ONSET numeric,
              READMINISTRATION numeric,
              DRUG_STOPPED numeric,
              SEMIOLOGY_OUTCOME numeric,
              COMPLEMENTARY_TEST numeric,
              OTHER_EXPLANATION numeric,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,EVENT_SEQ_NUM,AGENT_SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_event_nature"
          "CREATE TABLE rm_case_event_nature (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              EVENT_SEQ_NUM numeric NOT NULL,
              EVT_NATURE_ID numeric NOT NULL,
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              DELETED_FLAG numeric(1) NOT NULL,
              REVISION_DELETE_FLAG numeric,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_event_product_rptblty"
          "CREATE TABLE rm_case_event_product_rptblty (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              PROD_SEQ_NUM numeric NOT NULL,
              EVENT_SEQ_NUM numeric,
              REPORTABILITY numeric,
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,PROD_SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_event_rech_prod"
          "CREATE TABLE rm_case_event_rech_prod (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              EVENT_SEQ_NUM numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              PRODUCT_SEQ_NUM numeric,
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,EVENT_SEQ_NUM,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_followup"
          "CREATE TABLE rm_case_followup (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              RECEIPT_DATE timestamp,
              SAFETY_DATE timestamp,
              SIGNIFICANT numeric(1),
              AUDITLOG_TYPE numeric,
              TIME_STAMP timestamp,
              DELETED timestamp,
              SIGNIFICANT_DEVICE numeric(1),
              DATA_CLEANUP numeric(1),
              JUSTIFICATION varchar(1000),
              JUSTIFICATION_ID numeric,
              JUSTIFICATION_J varchar(1000),
              JUST_RECEIPT_DATE_J varchar(1000),
              RECEIPT_DATE_J timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_hosp"
          "CREATE TABLE rm_case_hosp (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              START_DATE timestamp,
              END_DATE timestamp,
              DURATION numeric,
              PROLONGED numeric,
              SUMMARY numeric,
              EVENT_CAUSED numeric,
              START_DATE_RES numeric,
              START_DATE_PARTIAL varchar(20),
              END_DATE_RES numeric,
              END_DATE_PARTIAL varchar(20),
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_justifications"
          "CREATE TABLE rm_case_justifications (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              FIELD_ID numeric NOT NULL,
              PRIMARY_SEQ_NUM numeric NOT NULL,
              ALT_SEQ_NUM numeric NOT NULL,
              J_TEXT varchar(1000),
              J_TEXT_J varchar(1000),
              UPDATED_TIME timestamp,
              DELETED timestamp,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,FIELD_ID,PRIMARY_SEQ_NUM,ALT_SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

    { "rm_case_lab_data"
          "CREATE TABLE rm_case_lab_data (
              ENTERPRISE_ID numeric NOT NULL,
              CASE_ID numeric NOT NULL,
              SEQ_NUM numeric NOT NULL,
              LAB_TEST_ID numeric,
              TEST_DATE timestamp,
              SORT_ID numeric,
              ASSESSMENT numeric,
              TEST_DATE_RES numeric(4),
              RESULTS varchar(50),
              NORM_HIGH varchar(50),
              NORM_LOW varchar(50),
              TEST_DATE_PARTIAL varchar(20),
              RESULT varchar(20),
              UNIT varchar(35),
              LAB_TEST_NAME varchar(250),
              DELETED timestamp,
              NOTES text,
              NOTES_J text,
              PT_CODE varchar(50),
              LLT_CODE varchar(50),
              HLT_CODE varchar(50),
              HLGT_CODE varchar(50),
              SOC_CODE varchar(50),
              SYN_CODE numeric,
              DICT_ID numeric,
              LLT varchar(250),
              HLT varchar(250),
              HLGT varchar(250),
              SOC varchar(250),
              CODE_STATUS numeric,
              TEST_REPTD varchar(250),
              UNIT_ID numeric,
              CODE_STATUS_J numeric,
              HLGT_J varchar(250),
              HLT_J varchar(250),
              LAB_TEST_NAME_J varchar(250),
              LLT_CODE_J varchar(50),
              LLT_J varchar(250),
              RESULTS_J varchar(50),
              RESULT_J varchar(20),
              SOC_J varchar(250),
              TEST_REPTD_J varchar(250),
              SYN_CODE_J numeric,
              DLP_REVISION_NUMBER numeric NOT NULL,
              REVISION_DELETE_FLAG numeric,
              DELETED_FLAG numeric(1) NOT NULL,
              EFFECTIVE_START_DATE timestamp NOT NULL,
              EFFECTIVE_END_DATE timestamp NOT NULL,
              PRIMARY KEY (ENTERPRISE_ID,CASE_ID,SEQ_NUM,DLP_REVISION_NUMBER)
          ); " }

  ] ))

(def dummy 

    { ""
          "
          " }

)
