SELECT
    a.ENTERPRISE_ID, a.CASE_ID, a.SEQ_NUM, a.DESC_REPTD, a.DESC_CODED, a.DIAGNOSIS,
    a.ONSET, a.ONSET_RES, a.ONSET_DELAY, a.STOP_DATE, a.STOP_DATE_RES, a.DURATION,
    a.ONSET_LATENCY, a.EVT_INTENSITY_ID, a.EVT_FREQ_ID, a.TREATED, a.STUDY_RELATED,
    a.RECHALL_RELATED, a.PROD_SEQ_NUM, a.EVT_OUTCOME_ID, a.RECEIPT_DATE,
    a.RPT_SERIOUS, a.SC_DEATH, a.SC_HOSP, a.SC_CONG_ANOM, a.SC_THREAT, a.SC_DISABLE,
    a.SC_INT_REQ, a.SC_OTHER, a.SC_OTHER_TEXT, a.ART_CODE, a.PREF_TERM, a.INC_TERM,
    a.BODY_SYS, a.MED_SERIOUS, a.PAST_HIST, a.DICT_ID, a.DICT_KEY, a.CODE_STATUS,
    a.SERIOUSNESS, a.SORT_ID, a.ONSET_DATE_PARTIAL, a.STOP_DATE_PARTIAL, a.EFFICACY,
    a.DISEASE, a.WITHDRAWAL, a.HLGT, a.HLT, a.HLT_CODE, a.HLGT_CODE, a.SOC_CODE,
    a.STUDY_DROPPED, a.INC_CODE, a.ONSET_MINUTES, a.DELAY_MINUTES, b.VERSION_NUM,
    b.EFFECTIVE_START_DATE, b.EFFECTIVE_END_DATE
FROM
    ArgusMart.RM_CASE_EVENT AS a, ArgusMart.CASE_VERSION_TABLE AS b
WHERE
    (a.CASE_ID = b.CASE_ID) AND 
    (a.ENTERPRISE_ID = b.ENTERPRISE_ID) AND 
    (a.DELETED_FLAG = convert(0, bigdecimal)) AND 
    (convert(a.EFFECTIVE_START_DATE, timestamp) <= b.EFFECTIVE_START_DATE) AND 
    (convert(a.EFFECTIVE_END_DATE, timestamp) > b.EFFECTIVE_START_DATE)

--------------------

