SELECT
    a.ENTERPRISE_ID, a.CASE_ID, a.SEQ_NUM, a.MEDIA_ID, a.OCCUPATION_ID, a.HCP_FLAG,
    a.PRIMARY_CONTACT, a.CORR_CONTACT, a.REPORTER_TYPE, a.INTERMEDIARY_ID, a.RPT_SENT,
    a.SORT_ID, a.CONFIDENTIAL, a.COUNTRY_ID, a.REPORTER_ID, a.INSTITUTION,
    a.INSTITUTION_ID, b.VERSION_NUM, b.EFFECTIVE_START_DATE, b.EFFECTIVE_END_DATE
FROM
    ArgusMart.RM_CASE_REPORTERS AS a, ArgusMart.CASE_VERSION_TABLE AS b
WHERE
    (a.CASE_ID = b.CASE_ID) AND 
    (a.ENTERPRISE_ID = b.ENTERPRISE_ID) AND 
    (a.DELETED_FLAG = convert(0, bigdecimal)) AND 
    (convert(a.EFFECTIVE_START_DATE, timestamp) <= b.EFFECTIVE_START_DATE) AND 
    (convert(a.EFFECTIVE_END_DATE, timestamp) > b.EFFECTIVE_START_DATE)

--------------------

