SELECT
    a.CASE_ID, a.LISTEDNESS, a.OUTCOME, a.SERIOUSNESS, a.AGENT_SUSPECT,
    a.COMPANY_DIAGNOSIS, b.VERSION_NUM, b.EFFECTIVE_START_DATE, b.EFFECTIVE_END_DATE,
    a.ENTERPRISE_ID
FROM
    ArgusMart.RM_CASE_ASSESS AS a, ArgusMart.CASE_VERSION_TABLE AS b
WHERE
    (a.CASE_ID = b.CASE_ID) AND 
    (a.ENTERPRISE_ID = b.ENTERPRISE_ID) AND 
    (a.DELETED_FLAG = convert(0, bigdecimal)) AND 
    (convert(a.EFFECTIVE_START_DATE, timestamp) <= b.EFFECTIVE_START_DATE) AND 
    (convert(a.EFFECTIVE_END_DATE, timestamp) > b.EFFECTIVE_START_DATE)
