SELECT
    A.CASE_ID, A.SEQ_NUM, A.LATENCY_SECONDS, A.RECHALL_STOP, A.RECHALL_START,
    A.TOTAL_DOSE, A.TAMPERING, A.OVERDOSE, A.PROTOCOL, A.RECHALL_OUTCOME,
    A.RECHALLENGE, A.N_SIBLINGS, A.CUMULATIVE_DOSE_UNIT_ID, A.OBTAIN_DRUG_COUNTRY_ID,
    A.DRUG_AUTH_COUNTRY_ID, A.CUMULATIVE_DOSE, A.ABUSE, A.CONTRAIND, A.DECHALLENGE,
    A.ACT_TAKEN_ID, A.CONC_UNITS_ID, A.FORMULATION_ID, A.CONCENTRATION, A.SEVERITY_ID,
    A.INTERACTION, A.PREV_USE, A.DECHALL_DATE, A.FIRST_DOSE, A.LAST_DOSE,
    A.DURATION_SECONDS, B.VERSION_NUM, B.EFFECTIVE_START_DATE, B.EFFECTIVE_END_DATE,
    A.ENTERPRISE_ID, A.FIRST_DOSE_PARTIAL, A.LAST_DOSE_PARTIAL
FROM
    ArgusMart.RM_CASE_PROD_DRUGS AS A, ArgusMart.CASE_VERSION_TABLE AS B
WHERE
    (A.CASE_ID = B.CASE_ID) AND 
    (A.ENTERPRISE_ID = B.ENTERPRISE_ID) AND 
    (A.DELETED_FLAG = 0) AND 
    (A.EFFECTIVE_START_DATE <= B.EFFECTIVE_START_DATE) AND 
    (A.EFFECTIVE_END_DATE > B.EFFECTIVE_START_DATE)
