SELECT
    ArgusMart.RM_LM_PRODUCT.ENTERPRISE_ID, ArgusMart.RM_LM_PRODUCT.PRODUCT_ID,
    ArgusMart.RM_LM_PRODUCT.PROD_NAME, ArgusMart.RM_LM_PRODUCT.FAMILY_ID,
    ArgusMart.RM_LM_PRODUCT.FORMULATION_ID, ArgusMart.RM_LM_PRODUCT.MANUFACTURER_ID,
    ArgusMart.RM_LM_PRODUCT.CONCENTRATION, ArgusMart.RM_LM_PRODUCT.CONC_UNIT_ID,
    ArgusMart.RM_LM_PRODUCT.INDICATION_ID, ArgusMart.RM_LM_PRODUCT.CODE_DICT,
    ArgusMart.RM_LM_PRODUCT.INDICATION_TEXT, ArgusMart.RM_LM_PRODUCT.INTL_BIRTH_DATE,
    ArgusMart.RM_LM_PRODUCT.MODEL_NO, ArgusMart.RM_LM_PRODUCT.DRUG_CODE,
    ArgusMart.RM_LM_PRODUCT.PROD_GENERIC_NAME, ArgusMart.RM_LM_PRODUCT.IND_LLT_CODE,
    ArgusMart.RM_LM_PRODUCT.IND_LLT, ArgusMart.RM_LM_PRODUCT.IND_HLT_CODE,
    ArgusMart.RM_LM_PRODUCT.IND_HLT, ArgusMart.RM_LM_PRODUCT.IND_HLGT_CODE,
    ArgusMart.RM_LM_PRODUCT.IND_HLGT, ArgusMart.RM_LM_PRODUCT.IND_SOC_CODE,
    ArgusMart.RM_LM_PRODUCT.IND_SOC, ArgusMart.RM_LM_PRODUCT.IND_SYN_CODE,
    ArgusMart.RM_LM_PRODUCT.IND_CODE_STATUS, ArgusMart.RM_LM_PRODUCT.PROD_NAME_ABBRV,
    ArgusMart.RM_LM_PRODUCT.IND_CODED, ArgusMart.RM_LM_PRODUCT.IND_REPTD
FROM
    ArgusMart.RM_LM_PRODUCT
WHERE
    ArgusMart.RM_LM_PRODUCT.DELETED IS NULL
