rm_case_narrative.enterprise_id                       -- numeric not null,
rm_case_narrative.case_id                             -- numeric not null,
rm_case_narrative.abbrev_narrative                    -- text,
rm_case_narrative.abbrev_narrative_j                  -- text,
rm_case_narrative.narrative                           -- text,
rm_case_narrative.narrative_j                         -- text,
rm_case_narrative.deleted                             -- timestamp,
rm_case_narrative.dlp_revision_number                 -- numeric not null,
rm_case_narrative.revision_delete_flag                -- numeric,
rm_case_narrative.deleted_flag                        -- numeric(1) not null,
rm_case_narrative.effective_start_date                -- timestamp not null,
rm_case_narrative.effective_end_date                  -- timestamp not null,
