--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_PROD_DRUGS
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_PROD_DRUGS" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"SEQ_NUM" NUMBER, 
	"FORMULATION_ID" NUMBER, 
	"CONCENTRATION" VARCHAR2(10 CHAR), 
	"CONC_UNITS_ID" NUMBER, 
	"ACT_TAKEN_ID" NUMBER, 
	"SEVERITY_ID" NUMBER, 
	"INTERACTION" NUMBER, 
	"CONTRAIND" NUMBER, 
	"FIRST_DOSE" DATE, 
	"FIRST_DOSE_RES" NUMBER, 
	"LAST_DOSE" DATE, 
	"LAST_DOSE_RES" NUMBER, 
	"TOTAL_DOSE" NUMBER(22,7), 
	"TOT_DOSE_UNIT_ID" NUMBER, 
	"PREV_USE" NUMBER, 
	"ABUSE" NUMBER, 
	"OVERDOSE" NUMBER, 
	"PROTOCOL" NUMBER, 
	"DECHALLENGE" NUMBER, 
	"DECHALL_DATE" DATE, 
	"RECHALLENGE" NUMBER, 
	"RECHALL_START" DATE, 
	"RECHALL_STOP" DATE, 
	"RECHALL_OUTCOME" NUMBER, 
	"SORT_ID" NUMBER, 
	"B_WEIGHT_GRAMS" NUMBER, 
	"N_SIBLINGS" NUMBER, 
	"B_WEIGHT_OZS" NUMBER, 
	"FIRST_DOSE_PARTIAL" VARCHAR2(20 CHAR), 
	"LAST_DOSE_PARTIAL" VARCHAR2(20 CHAR), 
	"TAMPERING" NUMBER(4,0), 
	"CUMULATIVE_DOSE" NUMBER(22,7), 
	"CUMULATIVE_DOSE_UNIT" VARCHAR2(10 CHAR), 
	"DELETED" DATE, 
	"UD_TEXT_1" VARCHAR2(100 CHAR), 
	"UD_TEXT_2" VARCHAR2(100 CHAR), 
	"UD_TEXT_3" VARCHAR2(100 CHAR), 
	"UD_TEXT_4" VARCHAR2(100 CHAR), 
	"UD_TEXT_5" VARCHAR2(100 CHAR), 
	"UD_TEXT_6" VARCHAR2(100 CHAR), 
	"UD_TEXT_7" VARCHAR2(100 CHAR), 
	"UD_TEXT_8" VARCHAR2(100 CHAR), 
	"UD_TEXT_9" VARCHAR2(100 CHAR), 
	"UD_TEXT_10" VARCHAR2(100 CHAR), 
	"UD_TEXT_11" VARCHAR2(100 CHAR), 
	"UD_TEXT_12" VARCHAR2(100 CHAR), 
	"UD_DATE_1" DATE, 
	"UD_DATE_2" DATE, 
	"UD_DATE_3" DATE, 
	"UD_DATE_4" DATE, 
	"UD_DATE_5" DATE, 
	"UD_DATE_6" DATE, 
	"UD_DATE_7" DATE, 
	"UD_DATE_8" DATE, 
	"UD_DATE_9" DATE, 
	"UD_DATE_10" DATE, 
	"UD_DATE_11" DATE, 
	"UD_DATE_12" DATE, 
	"UD_NUMBER_1" NUMBER(30,10), 
	"UD_NUMBER_2" NUMBER(30,10), 
	"UD_NUMBER_3" NUMBER(30,10), 
	"UD_NUMBER_4" NUMBER(30,10), 
	"UD_NUMBER_5" NUMBER(30,10), 
	"UD_NUMBER_6" NUMBER(30,10), 
	"UD_NUMBER_7" NUMBER(30,10), 
	"UD_NUMBER_8" NUMBER(30,10), 
	"UD_NUMBER_9" NUMBER(30,10), 
	"UD_NUMBER_10" NUMBER(30,10), 
	"UD_NUMBER_11" NUMBER(30,10), 
	"UD_NUMBER_12" NUMBER(30,10), 
	"CUMULATIVE_DOSE_UNIT_ID" NUMBER, 
	"OBTAIN_DRUG_COUNTRY_ID" NUMBER, 
	"DRUG_AUTH_COUNTRY_ID" NUMBER, 
	"DURATION_SECONDS" NUMBER, 
	"LATENCY_SECONDS" NUMBER, 
	"DELAY_SECONDS" NUMBER, 
	"UD_TEXT_1_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_2_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_3_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_4_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_5_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_6_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_7_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_8_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_9_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_10_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_11_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_12_J" VARCHAR2(100 CHAR), 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_PROD_DRUGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_PROD_DRUGS" ON "MART_USER"."RM_CASE_PROD_DRUGS" ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_PROD_DRUGS
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_PROD_DRUGS" ON "MART_USER"."RM_CASE_PROD_DRUGS" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_PROD_DRUGS
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_PROD_DRUGS" ADD CONSTRAINT "PK_RM_CASE_PROD_DRUGS" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_PROD_DRUGS" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PROD_DRUGS" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PROD_DRUGS" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_PROD_DRUGS" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
