--------------------------------------------------------
--  File created - Monday-April-06-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_REV_MASTER
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_REV_MASTER" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"DLP_REVISION_NUMBER" NUMBER, 
	"CASE_LOCKED" NUMBER, 
	"DATA_CLEANUP" NUMBER, 
	"CASE_REVISION_DATE" DATE, 
	"DATE_LOCKED" DATE, 
	"SITE_ID" NUMBER, 
	"STATE_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"EFFECTIVE_RECEIPT_DATE" DATE, 
	"EFFECTIVE_RECEIPT_DATE_J" DATE, 
	"EFFECTIVE_SAFETY_DATE" DATE, 
	"EFFECTIVE_TIME_STAMP" DATE, 
	"DCM_XREF_NUM" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_REV_MASTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_REV_MASTER" ON "MART_USER"."RM_CASE_REV_MASTER" ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_REV_MASTER
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_REV_MASTER" ADD CONSTRAINT "PK_RM_CASE_REV_MASTER" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_REV_MASTER" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_REV_MASTER" MODIFY ("CASE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_REV_MASTER" MODIFY ("DLP_REVISION_NUMBER" NOT NULL ENABLE);
