--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_CASE_EVENT
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_CASE_EVENT" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"CASE_ID" NUMBER, 
	"SEQ_NUM" NUMBER, 
	"DESC_REPTD" VARCHAR2(250 CHAR), 
	"DESC_CODED" VARCHAR2(255 CHAR), 
	"DIAGNOSIS" NUMBER, 
	"ONSET" DATE, 
	"ONSET_RES" NUMBER, 
	"ONSET_DELAY" VARCHAR2(40 CHAR), 
	"STOP_DATE" DATE, 
	"STOP_DATE_RES" NUMBER, 
	"DURATION" VARCHAR2(40 CHAR), 
	"ONSET_LATENCY" VARCHAR2(40 CHAR), 
	"EVT_INTENSITY_ID" NUMBER, 
	"EVT_FREQ_ID" NUMBER, 
	"TREATED" NUMBER, 
	"STUDY_RELATED" NUMBER, 
	"RECHALL_RELATED" NUMBER, 
	"PROD_SEQ_NUM" NUMBER, 
	"EVT_OUTCOME_ID" NUMBER, 
	"RECEIPT_DATE" DATE, 
	"RPT_SERIOUS" NUMBER, 
	"SC_DEATH" NUMBER, 
	"SC_HOSP" NUMBER, 
	"SC_CONG_ANOM" NUMBER, 
	"SC_THREAT" NUMBER, 
	"SC_DISABLE" NUMBER, 
	"SC_INT_REQ" NUMBER, 
	"SC_OTHER" NUMBER, 
	"SC_OTHER_TEXT" VARCHAR2(30 CHAR), 
	"ART_CODE" VARCHAR2(30 CHAR), 
	"PREF_TERM" VARCHAR2(250 CHAR), 
	"INC_TERM" VARCHAR2(250 CHAR), 
	"BODY_SYS" VARCHAR2(250 CHAR), 
	"MED_SERIOUS" NUMBER, 
	"PAST_HIST" NUMBER, 
	"DICT_ID" NUMBER, 
	"DICT_KEY" VARCHAR2(20 CHAR), 
	"CODE_STATUS" NUMBER, 
	"SERIOUSNESS" NUMBER, 
	"SORT_ID" NUMBER, 
	"ONSET_DATE_PARTIAL" VARCHAR2(20 CHAR), 
	"STOP_DATE_PARTIAL" VARCHAR2(20 CHAR), 
	"EFFICACY" NUMBER, 
	"DISEASE" NUMBER, 
	"WITHDRAWAL" NUMBER, 
	"HLGT" VARCHAR2(250 CHAR), 
	"HLT" VARCHAR2(250 CHAR), 
	"HLT_CODE" VARCHAR2(30 CHAR), 
	"HLGT_CODE" VARCHAR2(30 CHAR), 
	"SOC_CODE" VARCHAR2(30 CHAR), 
	"STUDY_DROPPED" NUMBER(4,0), 
	"INC_CODE" VARCHAR2(30 CHAR), 
	"ONSET_MINUTES" NUMBER, 
	"DELAY_MINUTES" NUMBER, 
	"UD_TEXT_1" VARCHAR2(100 CHAR), 
	"UD_TEXT_2" VARCHAR2(100 CHAR), 
	"UD_TEXT_3" VARCHAR2(100 CHAR), 
	"UD_TEXT_4" VARCHAR2(100 CHAR), 
	"UD_TEXT_5" VARCHAR2(100 CHAR), 
	"UD_TEXT_6" VARCHAR2(100 CHAR), 
	"UD_TEXT_7" VARCHAR2(100 CHAR), 
	"UD_TEXT_8" VARCHAR2(100 CHAR), 
	"UD_TEXT_9" VARCHAR2(100 CHAR), 
	"UD_TEXT_10" VARCHAR2(100 CHAR), 
	"UD_TEXT_11" VARCHAR2(100 CHAR), 
	"UD_TEXT_12" VARCHAR2(100 CHAR), 
	"UD_DATE_1" DATE, 
	"UD_DATE_2" DATE, 
	"UD_DATE_3" DATE, 
	"UD_DATE_4" DATE, 
	"UD_DATE_5" DATE, 
	"UD_DATE_6" DATE, 
	"UD_DATE_7" DATE, 
	"UD_DATE_8" DATE, 
	"UD_DATE_9" DATE, 
	"UD_DATE_10" DATE, 
	"UD_DATE_11" DATE, 
	"UD_DATE_12" DATE, 
	"UD_NUMBER_1" NUMBER(30,10), 
	"UD_NUMBER_2" NUMBER(30,10), 
	"UD_NUMBER_3" NUMBER(30,10), 
	"UD_NUMBER_4" NUMBER(30,10), 
	"UD_NUMBER_5" NUMBER(30,10), 
	"UD_NUMBER_6" NUMBER(30,10), 
	"UD_NUMBER_7" NUMBER(30,10), 
	"UD_NUMBER_8" NUMBER(30,10), 
	"UD_NUMBER_9" NUMBER(30,10), 
	"UD_NUMBER_10" NUMBER(30,10), 
	"UD_NUMBER_11" NUMBER(30,10), 
	"UD_NUMBER_12" NUMBER(30,10), 
	"DETAILS" CLOB, 
	"DETAILS_J" CLOB, 
	"SYN_CODE" NUMBER, 
	"DELETED" DATE, 
	"STUDY_RELATED_REPTD" NUMBER(1,0), 
	"DURATION_UNIT_E2B" NUMBER, 
	"ONSET_LATENCY_UNIT_E2B" NUMBER, 
	"ONSET_DELAY_UNIT_E2B" NUMBER, 
	"DURATION_SECONDS" NUMBER, 
	"ONSET_LATENCY_SECONDS" NUMBER, 
	"ONSET_DELAY_SECONDS" NUMBER, 
	"BODY_SYS_J" VARCHAR2(250 CHAR), 
	"CODE_STATUS_J" NUMBER, 
	"DESC_CODED_J" VARCHAR2(255 CHAR), 
	"DESC_REPTD_J" VARCHAR2(250 CHAR), 
	"HLGT_J" VARCHAR2(250 CHAR), 
	"HLT_J" VARCHAR2(250 CHAR), 
	"INC_CODE_J" VARCHAR2(30 CHAR), 
	"INC_TERM_J" VARCHAR2(250 CHAR), 
	"PREF_TERM_J" VARCHAR2(250 CHAR), 
	"SC_OTHER_TEXT_J" VARCHAR2(30 CHAR), 
	"REPORT_EXCLUSION" NUMBER, 
	"REPORTABLE" NUMBER, 
	"UD_TEXT_1_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_2_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_3_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_4_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_5_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_6_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_7_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_8_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_9_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_10_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_11_J" VARCHAR2(100 CHAR), 
	"UD_TEXT_12_J" VARCHAR2(100 CHAR), 
	"SYN_CODE_J" NUMBER, 
	"INFECTION" NUMBER, 
	"RPT_EXCLUDE_CMT" VARCHAR2(1000 CHAR), 
	"RPT_EXCLUDE_CMT_J" VARCHAR2(1000 CHAR), 
	"DLP_REVISION_NUMBER" NUMBER, 
	"REVISION_DELETE_FLAG" NUMBER DEFAULT 0, 
	"DELETED_FLAG" NUMBER(1,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" 
 LOB ("DETAILS") STORE AS BASICFILE "RCE_DETAILS_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DETAILS_J") STORE AS BASICFILE "RCE_DETAILS_J_CLOB"(
  TABLESPACE "AM_MART_LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_RM_CASE_EVENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_CASE_EVENT" ON "MART_USER"."RM_CASE_EVENT" ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  DDL for Index I_RM_CASE_EVENT
--------------------------------------------------------

  CREATE INDEX "MART_USER"."I_RM_CASE_EVENT" ON "MART_USER"."RM_CASE_EVENT" ("ENTERPRISE_ID", "CASE_ID", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_CASE_EVENT
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_CASE_EVENT" ADD CONSTRAINT "PK_RM_CASE_EVENT" PRIMARY KEY ("ENTERPRISE_ID", "CASE_ID", "SEQ_NUM", "DLP_REVISION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT" MODIFY ("DELETED_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_CASE_EVENT" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
