--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_LM_PRODUCT_FAMILY
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_LM_PRODUCT_FAMILY" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"FAMILY_ID" NUMBER, 
	"NAME" VARCHAR2(40 CHAR), 
	"PRIMARY_VIEW" NUMBER, 
	"DELETED" DATE, 
	"PRODUCT_GROUP_ID" NUMBER, 
	"COMMENTS" VARCHAR2(1000 CHAR), 
	"SEARCH_EQUATION_NUMBER" VARCHAR2(10 CHAR), 
	"NAME_J" VARCHAR2(40 CHAR), 
	"COMMENTS_J" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_LM_PRODUCT_FAMILY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_LM_PRODUCT_FAMILY" ON "MART_USER"."RM_LM_PRODUCT_FAMILY" ("ENTERPRISE_ID", "FAMILY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_LM_PRODUCT_FAMILY
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_LM_PRODUCT_FAMILY" ADD CONSTRAINT "PK_RM_LM_PRODUCT_FAMILY" PRIMARY KEY ("ENTERPRISE_ID", "FAMILY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_LM_PRODUCT_FAMILY" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
