--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_LM_COUNTRIES
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_LM_COUNTRIES" 
   (	"ENTERPRISE_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','enterprise_id'), 
	"COUNTRY_ID" NUMBER, 
	"COUNTRY" VARCHAR2(50 CHAR), 
	"A2" VARCHAR2(2 CHAR), 
	"A3" VARCHAR2(3 CHAR), 
	"NUM" NUMBER, 
	"PROTECTED" NUMBER, 
	"DELETED" DATE, 
	"COUNTRY_GROUP_ID" NUMBER, 
	"COUNTRY_GROUP" VARCHAR2(50 CHAR), 
	"COUNTRY_J" VARCHAR2(50 CHAR), 
	"GROUP_2_COUNTRY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_LM_COUNTRIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_LM_COUNTRIES" ON "MART_USER"."RM_LM_COUNTRIES" ("ENTERPRISE_ID", "COUNTRY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_LM_COUNTRIES
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_LM_COUNTRIES" ADD CONSTRAINT "PK_RM_LM_COUNTRIES" PRIMARY KEY ("ENTERPRISE_ID", "COUNTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_LM_COUNTRIES" MODIFY ("ENTERPRISE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_LM_COUNTRIES" MODIFY ("COUNTRY" NOT NULL ENABLE);
