--------------------------------------------------------
--  File created - Saturday-April-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RM_MEDDRA_SMQ_CONTENT
--------------------------------------------------------

  CREATE TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" 
   (	"GLOBAL_DICT_ID" NUMBER DEFAULT SYS_CONTEXT('ARGUS_MART_CTX','meddra_global_dict_id'), 
	"SMQ_CODE" NUMBER, 
	"TERM_CODE" NUMBER, 
	"TERM_LEVEL" NUMBER, 
	"TERM_SCOPE" NUMBER, 
	"TERM_CATEGORY" VARCHAR2(1 CHAR), 
	"TERM_WEIGHT" NUMBER, 
	"TERM_STATUS" VARCHAR2(1 CHAR), 
	"TERM_ADDITION_VERSION" VARCHAR2(5 CHAR), 
	"TERM_LAST_MODIFIED_VERSION" VARCHAR2(5 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_DATA_01" ;
--------------------------------------------------------
--  DDL for Index PK_RM_MEDDRA_SMQ_CONTENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "MART_USER"."PK_RM_MEDDRA_SMQ_CONTENT" ON "MART_USER"."RM_MEDDRA_SMQ_CONTENT" ("GLOBAL_DICT_ID", "SMQ_CODE", "TERM_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01" ;
--------------------------------------------------------
--  Constraints for Table RM_MEDDRA_SMQ_CONTENT
--------------------------------------------------------

  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" ADD CONSTRAINT "PK_RM_MEDDRA_SMQ_CONTENT" PRIMARY KEY ("GLOBAL_DICT_ID", "SMQ_CODE", "TERM_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AM_MART_INDEX_01"  ENABLE;
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("GLOBAL_DICT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_LEVEL" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_SCOPE" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_CATEGORY" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_WEIGHT" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_ADDITION_VERSION" NOT NULL ENABLE);
 
  ALTER TABLE "MART_USER"."RM_MEDDRA_SMQ_CONTENT" MODIFY ("TERM_LAST_MODIFIED_VERSION" NOT NULL ENABLE);
